### ISSUE TITLE
Can't use the instance of the contract deployed using factory contract

### ISSUE THREAD

**Issue by rahulthakkar796** [tronprotocol/tronweb#101]
I'm using a factory contract to deploy contracts but unable to use an instance of that deployed contract using tronweb.

I have tried both contract().at('contract _address') and contract(abi,'contract_address') methods but getting "Failed to execute error" on any method call of that contract.

according to the feedback from some people, it looks like it's an issue of tronweb.

**Comment by CQBinh** [comment]
Try this way:
```
var contractAddress = 'contract_address';

var functionSelector = 'function_name(uint256)';

var parameter = [
    {type: 'uint256', value: 100}
]
var options = {};

transaction = await tronWeb.transactionBuilder.triggerConstantContract(contractAddress, functionSelector, options,parameter);
```

**Comment by Linge19494492** [comment]
@CQBinh There are two parameters

like this？
  var parameter = [
    {type: 'uint256', value: 100}
   {type: 'address', value: TEkU1EQGYYWT5qTzZM9MKT7HsE6aHRh1e9}
]
