### ISSUE TITLE
How to pass a tuple as an argument?

### ISSUE THREAD

**Issue by Agilulfo1820** [tronprotocol/tronweb#103]
I need to call a function in my smart contract that accept a tuple as a parameter, but when I do I always get this message:
```
error Error: types/value length mismatch (coderType="tuple", value=["EMP","DSSADA-DASDASDAS-DSADSAD"], version=4.0.48)
```

This is how I do it:
```
 let data = [
            'EMP',
            'DSSADA-DASDASDAS-DSADSAD'
        ]
        let result = await contract.addEmployee(data).send();
```

**Comment by summertanh** [comment]
data param is an array which likes as follows:
data = [{type: 'string', value: 'EMP'}, {type: 'string', value: 'DSSADA-DASDASDAS-DSADSAD'}]
