### ISSUE TITLE
calling method on Smart contract without ABI, Failed to Execute error

### ISSUE THREAD

**Issue by andrearizzi77** [tronprotocol/tronweb#107]
Hi,
I am trying to call some methods (pure view) on Justswap smart contract. As you probably know the justswap smart contract was created by a factory contract and for this reason is without ABI.
I have tried to wrap the contract object with the Justswap ABI and then calling a constant view method without success.
I have tried to call the same method on Justswap template contract and it works. 

it seems tronweb contract object failed to setup correctly if the smart contract is without ABI.

below my code, if I change the justswap contract with his template (address: TDNbPAZh1cWvdJDnJ5M56eCwbxFm7b1x8V) works!

const TronWeb = require('tronweb');
const TronGrid = require('trongrid');
const HttpProvider = TronWeb.providers.HttpProvider;
const fullNode = new HttpProvider("https://api.trongrid.io");
const solidityNode = new HttpProvider("https://api.trongrid.io");
const eventServer = new HttpProvider("https://api.trongrid.io");
const privateKey = "3481E79956D4BD95F358AC96D151C976392FC4E3FC132F78A847906DE588C145";
const tronWeb = new TronWeb(fullNode,solidityNode,eventServer,privateKey);

var testContract;
var factoryAddr;

// ABI, a portion of ABI, only for testing the factoryAddress call method. To be replaced with the complete Justswap ABI
const JSABI = [{
	"outputs":[{"type":"address"}],
	"constant":true,
	"name":"factoryAddress",
	"stateMutability":"View",
	"type":"Function"
}]

// initiate justswap contract with a specified ABI
async function initiateContract() {
	testContract = await tronWeb.contract(JSABI,"TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE");
}

async function methodCalling() {
	try {
		factoryAddr = await testContract.factoryAddress().call();  //<------ here we have the error, 
		factoryAddr = tronWeb.address.fromHex(factoryAddr);
	}
	catch (error) {
		console.log(error); 
	}
}

function init() {
   await initiateContract();
   await methodCalling();
}

init();

**Comment by coder-van** [comment]
see #104 , you can fixed in your self workspace
this.tronWeb.transactionBuilder.triggerSmartContract() -> this.tronWeb.transactionBuilder.triggerConstantContract()

**Comment by llwslc** [comment]
try
```
await testContract.factoryAddress().call({_isConstant: true});
```
