### ISSUE TITLE
How to listen for events from contract that created from other contract

### ISSUE THREAD

**Issue by CQBinh** [tronprotocol/tronweb#108]
I'm trying to listen to events (or get events) from [justSwap](https://justswap.io/) liquidity pool. The pool contract is created from [JustswapFactory](https://tronscan.org/#/contract/TXk8rQSAvPvBBNtqSoY6nCfsXWCSSpTVQF/code).

My code:
```
const results = await tronGrid.contract.getEvents(poolAddress, options)
console.log(results.data.length) // 0
```

The code above is working with normal contract (deployed from tronbox), but CreatedFromContract.
I tried to find the answer on `tronWeb.transactionBuilder` but no luck.
So, How to listen for events from contract that created from other contract?

Thanks,

**Comment by summertanh** [comment]
unfortunately， Trongrid does not support listen to events of contract created by another contract as it has no abi code.
