### ISSUE TITLE
Can't trigger specific contracts (ones not returning ABI)

### ISSUE THREAD

**Issue by paniczklos** [tronprotocol/tronweb#113]
I'm not able to trigger call() on specific contracts - the one's that I have tested and are not working, are created by JustSwap factory (eg TUEYcyPAqc4hTg1fSuBCPc18vGWcJDECVw, TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE ).

I'm submitting it as an issue as:
a) the code below works with different contracts 
b) I can call the balanceOf() of JustSwap contracts using http API, so it might suggest tronweb problems with "unpublished ABI" contracts
c) it has also been reported on Tron developers Discord channel by several people.

The error that I get is ``` Failed to execute  ```

As I do only need the balanceOf() this is my defined abi : 
```
[
  {
    "constant": true,
    "inputs": [{ "name": "who", "type": "address" }],
    "name": "balanceOf",
    "outputs": [{ "name": "", "type": "uint256" }],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  }
]
```

and my code:

```
import ABI from "./abi.json";
const getDataToken = async (contractAddress, account, account2) => {
  try {
    let abi = ABI;
    const instance = await window.tronWeb.contract(abi, contractAddress);
    if (instance.balanceOf) {
      const tokenBalance = await instance.balanceOf(account).call();
      return {
        tokenBalance: (tokenBalance / Math.pow(10, 18)).toString(),
        tokenContract: instance,
      };
    }
  } catch (error) {
    console.log("error  getData  :" + error);
  }
};
```

**Comment by Benson0224** [comment]
there is no ABI if the contract is created by another contract. however,  you can use the below method to call the functions of the contract. 

```
var contractAddress = 'TXBm8wncj8k8ZCRxFzptxXKm2CuUbhorCQ';

var functionSelector = 'getTrxToTokenInputPrice(uint256)';


var parameter = [
    {type: 'uint256', value: 100}
]
var options = {};

transaction = await tronWeb.transactionBuilder.triggerConstantContract(contractAddress, functionSelector, options,parameter);
```

**Comment by grand-china** [comment]
> there is no ABI if the contract is created by another contract. however, you can use the below method to call the functions of the contract.
> 
> ```
> var contractAddress = 'TXBm8wncj8k8ZCRxFzptxXKm2CuUbhorCQ';
> 
> var functionSelector = 'getTrxToTokenInputPrice(uint256)';
> 
> 
> var parameter = [
>     {type: 'uint256', value: 100}
> ]
> var options = {};
> 
> transaction = await tronWeb.transactionBuilder.triggerConstantContract(contractAddress, functionSelector, options,parameter);
> ```



> 如果合同是由另一个合同创建的，则没有ABI。但是，您可以使用以下方法来调用合同的功能。
> 
> ```
> var contractAddress = 'TXBm8wncj8k8ZCRxFzptxXKm2CuUbhorCQ';
> 
> var functionSelector = 'getTrxToTokenInputPrice(uint256)';
> 
> 
> var parameter = [
>     {type: 'uint256', value: 100}
> ]
> var options = {};
> 
> transaction = await tronWeb.transactionBuilder.triggerConstantContract(contractAddress, functionSelector, options,parameter);
> ```



> there is no ABI if the contract is created by another contract. however, you can use the below method to call the functions of the contract.
> 
> ```
> var contractAddress = 'TXBm8wncj8k8ZCRxFzptxXKm2CuUbhorCQ';
> 
> var functionSelector = 'getTrxToTokenInputPrice(uint256)';
> 
> 
> var parameter = [
>     {type: 'uint256', value: 100}
> ]
> var options = {};
> 
> transaction = await tronWeb.transactionBuilder.triggerConstantContract(contractAddress, functionSelector, options,parameter);
> ```


现在的 tronweb js端 有bug，这个答案是可以使用的
