### ISSUE TITLE
tronweb是否支持匿名TRC20合约的调用

### ISSUE THREAD

**Issue by bajian** [tronprotocol/tronweb#116]
[匿名TRC20合约文档](https://github.com/tronprotocol/documentation-zh/blob/master/docs/mechanism-algorithm/shielded-TRC20-contract.md)
官方文档给出的是http API的例子，想问下tronweb是否支持，应该怎么实现？

**Comment by summertanh** [comment]
tronweb will support shielded transactions in next version, please look forward to it!
