### ISSUE TITLE
tronweb 3.2.0 can't run

### ISSUE THREAD

**Issue by love-ljy** [tronprotocol/tronweb#123]
The previous version 3.1.0 has been fine. After installing tronweb last night, I found that the version was upgraded to 3.2.0, and an error was reported when running locally.It took me a long time to find out that redjubjub-js introduced by tronweb has a problem。 TextDecoder is not a contructor
`const { TextDecoder } = require(String.raw`util`);

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });

cachedTextDecoder.decode();`in redjubjub-js。but i don't find the util，and the`TextDecoder` is in webapi already。so i don't understand why you do like this. This bug was fixed through my technical feedback to the community。

**Comment by summertanh** [comment]
So sorry for that, please use the version 3.2.1,  the version 3.2.0 will be deprecated soon.
