### ISSUE TITLE
Axios dependency failing npm audit

### ISSUE THREAD

**Issue by chrisc93** [tronprotocol/tronweb#127]
Please update the axios dependency
See https://www.npmjs.com/advisories/1594

**Comment by francovilla** [comment]
Yes, it is true, the problem is **High**

**Comment by summertanh** [comment]
we will update axios in next version

**Comment by chrisc93** [comment]
@summertanh there was a release 3 days ago and Axios was not updated. Please address this as it causes NPM audit failures.

**Comment by amochkin** [comment]
Still not updated

**Comment by drsavant-pub** [comment]
Four new version have been released since problem was reported and still Axios is not updated.

Update Axios as promised!

**Comment by summertanh** [comment]
already updated
