### ISSUE TITLE
CONTRACT_VALIDATE_ERROR

### ISSUE THREAD

**Issue by mitGen** [tronprotocol/tronweb#129]
Hi, I am creating an account using api "tronWeb.createAccount ()", but then I want to transfer to a new trx account through my NodeJS API, I sign the transaction "tronWeb.trx.sendTransaction ()" and insert the required parameters, but it gives an error "CONTRACT_VALIDATE_ERROR". Yes, this address has not been activated yet, but why can't I transfer via api from another TRX account???????

**Comment by newnya** [comment]
Do you need to just send TRX from an address to another?
Why don't you call `tronWeb.transactionBuilder.sendTrx(to, amount, from, options);` https://developers.tron.network/reference#sendtrx ?

**Comment by 1garo** [comment]
Running into the same problem, could you provide some info on this? @summertanh 

Maybe even something in the docs that I couldn't find. 

I'm trying exactly the same code that is here: https://developers.tron.network/docs/tron-protocol-transaction

**Comment by start940315** [comment]
please show us your code and not paste privateKey. There must be some mistakes in your code.
