### ISSUE TITLE
Sign transaction not working

### ISSUE THREAD

**Issue by abhisareen2002** [tronprotocol/tronweb#142]
Hi!
I have tried to sign a transaction multiple times. I don't think this issue is limited to tronweb for the following reasons:
1. I have tried using the sign transaction as the docs suggest, however that doesn't work. The transaction can be signed using multi-sign, but sign fails, which means the transaction object is correct and can be signed too. 
2. The HTTP API also fails while trying to call the GetTransactionSign method. It returns a 404. For the HTTP API user, i.e. me, this leaves no option as there is no multi-sign http api. For the HTTP API, I have tried using the sandbox for both making the transaction and signing it, and tried it using cURL too, however, the transaction can only be made. 

If there is someone else I should be contacting with this issue, please let me know.

**Comment by summertanh** [comment]
Hi, 
could you please show more info about the error or do you need to use multi-sign on TRON?

**Comment by abhisareen2002** [comment]
> Hi,
> could you please show more info about the error or do you need to use multi-sign on TRON?

You can try it out yourself. I talked to the SRs and they said that it's deprecated via HTTP due to security reasons. The only option seems multi-sign or sign the transactions locally by running a node...

One thing I hate about the docs are they're not regularly updated :/

**Comment by summertanh** [comment]
All right, thanks for your advice. We will update the doc in time.
