### ISSUE TITLE
Detect network type

### ISSUE THREAD

**Issue by xtovski** [tronprotocol/tronweb#149]
I am trying to figure out how to detect if the user has selected testnet (shasta or nile) or mainnet.
And I couldn't find anything related to this in API docs.
Also it seems there is nothing in source code of tronweb. 
Can someone advise me how can I detect network type?

**Comment by summertanh** [comment]
Sorry for that, TronWeb and the TRON have no network type, you can check the detail fullnode url to get your testnet or mainnet.
