### ISSUE TITLE
Snyk Reporting Severe (High) Vulnerability in elliptic@6.5.3 Dependency

### ISSUE THREAD

**Issue by drsavant-pub** [tronprotocol/tronweb#150]
Here is a link to [Snyk](https://snyk.io/advisor/npm-package/elliptic)

This issue was opened in August 2020 (last year), and promised to be resolved in the next version, The issue was then closed and never fixed.

Please fix this issue as promised 6-months ago by upgrading elliptic@6.5.3 TO elliptic@6.5.4 in your dependencies.  

That is all it will take.

**Comment by summertanh** [comment]
Sorry for that, TronWeb will update it in next version.

**Comment by summertanh** [comment]
https://github.com/tronprotocol/tronweb/pull/161
