### ISSUE TITLE
Get Address Transactions Errors 500, 502

### ISSUE THREAD

**Issue by VicAMMON** [tronprotocol/tronweb#152]
getTransactionsToAddress, getTransactionsFromAddress, getTransactionsRelated -- all of them return
500 error if node is api.trongrid.io
502 if node is api.shasta.trongrid.io
Could you help please .

**Comment by Benson0224** [comment]
Dear Developers,

We are informed by the TronGrid team that all GRPC interfaces access of TronGrid has supported API Key. To help projects smoothly migrate to the new version, we will allow one month of transition period where both access modes are acceptable. After the transition period ends, the original mode will be permanently disabled. Please switch to the new mode as soon as possible. We sincerely apologize for the inconvenience this may cause you. 

Please refer to the following documents on API Key application and use：

TronGrid Official Website: https://www.trongrid.io/
Acquire API Key: https://www.trongrid.io/
Use API Key: https://developers.tron.network/reference#how-to-use-api-keys

April 6, 2021

**Comment by VicAMMON** [comment]
I`m already using TRON-PRO-API-KEY.
But still 500 error.

**Comment by Benson0224** [comment]
> I`m already using TRON-PRO-API-KEY.
> But still 500 error.

Can you share more detail?  how did you visit the trongrid api?  at least it works on my side:  https://api.trongrid.io/wallet/gettransactionbyid?value=373bc5b9c11b0918ca3f9428f46508eee5ae4c63042b63ce6cbcc6ef6f6792d4
