### ISSUE TITLE
tronweb 离线签名

### ISSUE THREAD

**Issue by weihongyang** [tronprotocol/tronweb#155]
const TronWeb = require('tronweb')
const _tronWeb = new TronWeb({
    fullHost: 'https://api.shasta.trongrid.io',
    privateKey: '9ef2a2fbc8c85363c103dae0f912b88a257d01'
})

_tronWeb.trx.getBalance("THRAzV9kkc7HEPgrr2umwZqzZkv4HxPkTh").then(function(value){
    console.log(value)
})

function transfer(){
    _tronWeb.trx.getContract("TR2nP9BKLjSRU2FgAUBZ92jZh3dtXeqz31").then(function(contractInfo){
        var contractInstance= _tronWeb.contract(contractInfo.abi.entrys, contractInfo.contract_address);
        contractInstance.transfer("TZ2qxTbT4LEw2kw9x8ZH5u4yyG7usVWCq6", 100000000).send({
            shouldPollResponse: false,                
            feeLimit: 90000000,
            callValue: 0,
            from: "THRAzV9kkc7HEPgrr2umwZqzZkv4HxPkTh"
        }).then(function(result){
            console.log(result)
        });

    });

}

这个算是离线签名交易吗

**Comment by summertanh** [comment]
The above transaction is a TRC20 transfer and the signatures encapsulated internally are all local signatures
