### ISSUE TITLE
error 502 on calling a function on Tron smart contract to send trx to an address

### ISSUE THREAD

**Issue by maysun-mayer** [tronprotocol/tronweb#157]
Hi every one
I got this error on calling smart contract to send trx to an address on shasta,can anyone help me please?I'm using tronweb on chrome
![image](https://user-images.githubusercontent.com/3180456/114695746-34385f00-9d31-11eb-9a11-d17ef6ff9306.png)

**Comment by summertanh** [comment]
Maybe the fullnode server in shasta is not available at that time, you could try again.

**Comment by maysun-mayer** [comment]
@summertanh tnx for answer, but I tried many different times and every time I got these errors.
