### ISSUE TITLE
Doesn't work on iOS 12 and less

### ISSUE THREAD

**Issue by petr-like** [tronprotocol/tronweb#158]
Doesn't work on iOS 12 and lower
The wallet reads and receives information about the contract, but none of contract methods work, each method returns 0 code. 
maybe you can tell me how I can debug this and understand what is missing on these iOS versions

For example we can go to tronscan.org and open usdt contract and go to _Contract => Read or Write contract_ we can't get and see methods of contract. 
And such behavior with each contract

**Comment by Kim20021** [comment]
We have updated the version, please try again
