### ISSUE TITLE
Subscribe for account/network change

### ISSUE THREAD

**Issue by GyCtaB** [tronprotocol/tronweb#16]
Is there a way to subscribe for account/network change?

Something like 
```
tronWeb.on('accountChange', (newAccount) => {   
  // Callback
})

tronWeb.on('networkChange', (newNetwork) => {   
  // Callback
})
```

For now i'm using intervals to check for updates. And it's sure enough not the best way to do this.

**Comment by sullof** [comment]
Right now there is no way for that. But that sounds like a good idea.

**Comment by summertanh** [comment]
```js
window.addEventListener('message', (res) => {
        if (res.data.message && res.data.message.action == "setAccount") {
          if (window.tronWeb) {
            if (res.data.message.data.address != this.defaultAccount) {
              window.location.reload();
            }
          } else {
            window.location.reload();
          }
        }
        if (res.data.message && res.data.message.action == "setNode") {
          window.location.reload();
        }
    });

  }
```
you can listen the 'message' TronLink emitted. TronLink supports 'SetNode', 'SetAccount', 'SetChain' three events at present. May it can help you.

**Comment by toCryptoLeader** [comment]
> ```js
> window.addEventListener('message', (res) => {
>         if (res.data.message && res.data.message.action == "setAccount") {
>           if (window.tronWeb) {
>             if (res.data.message.data.address != this.defaultAccount) {
>               window.location.reload();
>             }
>           } else {
>             window.location.reload();
>           }
>         }
>         if (res.data.message && res.data.message.action == "setNode") {
>           window.location.reload();
>         }
>     });
> 
>   }
> ```
> 
> you can listen the 'message' TronLink emitted. TronLink supports 'SetNode', 'SetAccount', 'SetChain' three events at present. May it can help you.

Thanks!
