### ISSUE TITLE
Snyk Reporting TronWeb@3.2.6 Medium Severity Vulnerability in validator@10.11.0 Dependency

### ISSUE THREAD

**Issue by drsavant-pub** [tronprotocol/tronweb#165]
Here is a link to the [Snyk Report](https://snyk.io/test/npm/tronweb/3.2.6)

Please upgrade  validator@10.11.0 to validator@13.6.0.

This will fix the problem.

**Comment by Kim20021** [comment]
Okay, we will upgrade in the next version

**Comment by Benson0224** [comment]
Thanks for your contribution, as the issue is already fixed, we will close this issue. 

Please feel free to re-open it if you still see it. thanks.
