### ISSUE TITLE
Calculate the number of bytes in a transaction with TronWeb.

### ISSUE THREAD

**Issue by JessDotJS** [tronprotocol/tronweb#167]
Hello, is it possible to calculate the number of bytes in a transaction before broadcasting using TronWeb?

I found this info in the Tron Protocol docs but haven't been able to achieve the same with TronWeb/TronStationSDK: 
https://tronprotocol.github.io/documentation-en/faq/#how-to-calculate-the-number-of-bytes-of-transactions

Any help will be highly appreciated.

**Comment by Benson0224** [comment]
Currently, no API or method which can directly calculate the bytes. 

However, you can refer to this code to implement it by yourself. thanks. 

https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/java/org/tron/core/Wallet.java#L362
