### ISSUE TITLE
All transfer events do not come in.

### ISSUE THREAD

**Issue by igamezzhang** [tronprotocol/tronweb#168]
const trc20ContractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"； //mainnet USDT contract
let contract = await tronWeb.contract().at(trc20ContractAddress);

//contract.[eventname].watch(callback) enventname is the name of the event of the contract
await contract && contract.Transfer().watch((err, event) => {
  if(err)
    return console.error('Error with "Message" event:', err);
 
  console.group('New event received');
  console.log('- Contract Address:', event.contract);
  console.log('- Event Name:', event.name);
  console.log('- Transaction:', event.transaction);
  console.log('- Block number:', event.block);
  console.log('- Result:', event.result, '\n');
  console.groupEnd();
});

**Comment by Kim20021** [comment]
Please poll the API to implement
