### ISSUE TITLE
triggerSmartContract Sign Cannot read property 'contract' of undefined

### ISSUE THREAD

**Issue by liuhuanhui** [tronprotocol/tronweb#170]
```
 const wallet = await this.privateToWallet(privateKey);
    const parameter = [
      { type: "address", value: to },
      { type: "uint256", value: amount.toNumber() },
    ];
    const transaction = await rpc.transactionBuilder.triggerSmartContract(
      rpc.address.toHex(contractAddress),
      "transfer(address,uint256)",
      {},
      parameter,
      wallet.address
    );
    if (!transaction.result || !transaction.result.result) {
      throw new Error("交易创建失败！");
    }
    const sign = await rpc.trx.sign(transaction, privateKey);
    console.log(sign, "===sign");
```

**ERROR
2021-05-21 14:09:39,512 ERROR 94605 nodejs.TypeError: Cannot read property 'contract' of undefined**

**Comment by liuhuanhui** [comment]
> ` const wallet = await this.privateToWallet(privateKey); const parameter = [ { type: "address", value: to }, { type: "uint256", value: amount.toNumber() }, ]; const transaction = await rpc.transactionBuilder.triggerSmartContract( rpc.address.toHex(contractAddress), "transfer(address,uint256)", {}, parameter, wallet.address ); if (!transaction.result || !transaction.result.result) { throw new Error("交易创建失败！"); } const sign = await rpc.trx.sign(transaction, privateKey); console.log(sign, "===sign");`
> 
> **ERROR 2021-05-21 14:09:39,512 ERROR 94605 nodejs.TypeError: Cannot read property 'contract' of undefined**



> ` const wallet = await this.privateToWallet(privateKey); const parameter = [ { type: "address", value: to }, { type: "uint256", value: amount.toNumber() }, ]; const transaction = await rpc.transactionBuilder.triggerSmartContract( rpc.address.toHex(contractAddress), "transfer(address,uint256)", {}, parameter, wallet.address ); if (!transaction.result || !transaction.result.result) { throw new Error("交易创建失败！"); } const sign = await rpc.trx.sign(transaction, privateKey); console.log(sign, "===sign");`
> 
> **ERROR 2021-05-21 14:09:39,512 ERROR 94605 nodejs.TypeError: Cannot read property 'contract' of undefined**

**Comment by um1st** [comment]
If somebody is interested, the error was in line `const sign = await rpc.trx.sign(transaction, privateKey);`.
You need to change it to `const sign = await rpc.trx.sign(transaction.transacation, privateKey);`
