### ISSUE TITLE
How to get amount and token name in smart contract transactionInfo api

### ISSUE THREAD

**Issue by zebpay-peswani** [tronprotocol/tronweb#175]
``` 
 let w = await tronWeb.trx.getTransactionInfo('78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18')

console.log(w)

```
 This gives me internal_transactions list but no where it gives amount that was spent. it only gives owner_address and to_address
 in callValueInfo there is empty Array
```
{ id:
   '78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18',
  blockNumber: 30736090,
  blockTimeStamp: 1622666493000,
  contractResult: [ '' ],
  contract_address: '4110d718c22e8aa287bb8193aceaf3b90e66e90e0a',
  receipt:
   { origin_energy_usage: 10747,
     energy_usage_total: 10747,
     net_usage: 411,
     result: 'REVERT' },
  result: 'FAILED',
  resMessage: '524556455254206f70636f6465206578656375746564',
  internal_transactions:
   [ { hash:
        '5c8c2a2aa7aeaa6aa8d36262d06306afe3f7e2e068b15c1f64f8078a173e03fd',
       caller_address: '4110d718c22e8aa287bb8193aceaf3b90e66e90e0a',
       transferTo_address: '411fee56b32884a49155b7b6137ec0f1ee657455d5',
       callValueInfo: [Array],
       note: '63616c6c',
       rejected: true },
     { hash:
        'ce76d28311e60416905bbdd3093f64e2821f05f5bd149c94e913bcd290bdb8f5',
       caller_address: '411fee56b32884a49155b7b6137ec0f1ee657455d5',
       transferTo_address: '41af16843d1b471364576015e4062cdc3f2628eb62',
       callValueInfo: [Array],
       note: '63616c6c',
       rejected: true },
     { hash:
        '4f2cea425d875170cd4346293c0ed990bc06746fe3b7f0ddcd509bb9936579db',
       caller_address: '411fee56b32884a49155b7b6137ec0f1ee657455d5',
       transferTo_address: '41049909a380d589b9af76846280d3fcbeb67826f0',
       callValueInfo: [Array],
       note: '63616c6c',
       rejected: true } ] }
Waiting for the debugger to disconnect...

Process finished with exit code 0
```

This may be because it's value is 0 

IF you use this api 

[Tron web API for get Transaction Infro](https://apilist.tronscan.org/api/transaction-info?hash=78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18)

if I try `1c25bc75d0bebac2f3aa71c350d67c4eed56ec2501b72302ae6d0110dc40cf96` this id
then callValueInfo provide correct amount. but then it does not provide asset name.

[1c25bc75d0bebac2f3aa71c350d67c4eed56ec2501b72302ae6d0110dc40cf96](https://apilist.tronscan.org/api/transaction-info?hash=1c25bc75d0bebac2f3aa71c350d67c4eed56ec2501b72302ae6d0110dc40cf96)

above api gives result like

```

&nbsp; | "[{\"token_id\":\"_\",\"call_value\":10000000,\"tokenInfo\":{\"tokenId\":\"_\",\"tokenAbbr\":\"trx\",\"tokenName\":\"trx\",\"tokenDecimal\":6,\"tokenCanShow\":1,\"tokenType\":\"trc10\",\"tokenLogo\":\"https://coin.top/production/logo/trx.png\",\"vip\":false}}]"
-- | --

``
where it gives `tokenName`

I want that token name in `getTransactionInfo` api.

This gives correct info

**Comment by tronfamily** [comment]
TokenID: _ = TRX

In your case the array is empty: You can check it here:
https://api.trongrid.io/wallet/gettransactioninfobyid?value=78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18

If you look here: https://tronscan.org/#/transaction/78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18 , you see: 

importSeedFromThirdSugar(address _bettor,uint256 _seed,uint256 _salt,uint256 _sugar) and the value´s. You can extract this data from the data field.

https://api.trongrid.io/wallet/gettransactionbyid?value=78f3880618bb7459bcb7faaee05a81799220e9869def4d810f3fa4c2b9f26b18

"data":"49774683000000000000000000000000829cb3e4901b0d07a28929842d34d9e9d5b2a6742d67978fb14f74b3b524c8d270aae320b104f58d61fd99d1ceb30b2348c1956500000000000000000000000000000000000000000000000000000000000052de0000000000000000000000000000000000000000000000000000000b50c92600"

salt: 52de = 21214
sugar: b50c92600 = 48600000000

**Comment by zebpay-peswani** [comment]
Thanks I got it how to handle empty array

other important thing for me is 

```
https://api.trongrid.io/wallet/gettransactioninfobyid?value=1c25bc75d0bebac2f3aa71c350d67c4eed56ec2501b72302ae6d0110dc40cf96
```

This does not give token name or asset name.

How to ensure that the transaction is of trx only and not other assets

**Comment by tronfamily** [comment]
Two different queries exist in the TRON API:
gettransactioninfobyid
gettransactionbyid

Try this: https://api.trongrid.io/wallet/gettransactionbyid?value=1c25bc75d0bebac2f3aa71c350d67c4eed56ec2501b72302ae6d0110dc40cf96

5f or _ always mean TRX.

**Comment by Benson0224** [comment]
Thanks for your contribution, as the above comments already give the correct answer, we will close this issue now.

Please feel free to re-open it if you still see it. thanks.
