### ISSUE TITLE
Tronweb method calling issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/tronweb#182]
Hi,
Running private network in Tron. 
Creating TRC20 token contract and i was able to write contract but i can't call contract functionalities.

Tronweb npm version:  2.3.1
Node version: 11.0.0

![image](https://user-images.githubusercontent.com/48212011/124453396-f5043200-dda4-11eb-9047-469330d29166.png)

Kindly check and solve this issue asap.

**Comment by myzykj** [comment]
Hi,  please update the tronweb to the latest version and try,  thanks.

**Comment by summertanh** [comment]
Could you please show your contract code and call code?
