### ISSUE TITLE
EventServer in Tronweb

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/tronweb#184]
Hi,
What is the usage of 'EventServer' in Tronweb?
In private network, what port have to given?

const fullNode = 'https://<ip>:16667';
const solidityNode = 'http://<ip>:16668';
const eventServer = 'http://<ip>:0000';

Can anyone explain?

**Comment by llwslc** [comment]
Use [tron-eventquery](https://github.com/tronprotocol/tron-eventquery)
