### ISSUE TITLE
When writing test with tronWeb, how can we move time forward?

### ISSUE THREAD

**Issue by SimeonHr1stov** [tronprotocol/tronweb#190]
For example if I have a contract with a function that can be called once a day, how can I move time in the network to test this case. In openzeppelin there is a helper class that does this for the ethereum network. [time.js](https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/master/src/time.js)

How would we go about writing something like this with tronWeb?

**Comment by summertanh** [comment]
Sorry for that, at this stage, Tron does not have a server to support advanced block operations. In order to meet the requirements, you could use timed scripts to implement them.

**Comment by SimeonHr1stov** [comment]
Thank you, for the quick response.
