### ISSUE TITLE
trc20 transfer to "Ethereum" address destination works and sent to a random account

### ISSUE THREAD

**Issue by arkantos1482** [tronprotocol/tronweb#196]
We implemented our "**transfer USDT**" page so users can chose between **Tron network** and **Ethereum network**.
Some client mistakenly chose **Tron network** but with **Ethereum address**.
The strangest part is the transaction applied successfully but for a random address in Tron network which we don't have access to those random accounts. (even with private keys associated with Ethereum public keys)

let contract = await tronWeb.contract().at('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t')
let result = await contract.transfer('0x9CA16f4713Ff889157D5a2930c69e8C6AC61d1BF', 1)

but this is the transaction:
https://tronscan.org/#/transaction/5647dc5bfb63a887284eb642841f03bed73450cc187aa27d83422ea438e79e4b

this is the tron address: TQFPofPMs2y7ht9xgN7vN85g53RWGwHBgF
which has nothing to do with: 0x9CA16f4713Ff889157D5a2930c69e8C6AC61d1BF

**Comment by summertanh** [comment]
Yes, if you transfer to a ethereum address, tron will transfer asset successfully. As there is no fundamental difference
between  tron and eth accout address.  Actually when we run `tronWeb.address.toHex('TQFPofPMs2y7ht9xgN7vN85g53RWGwHBgF')`, the result is 0x419CA16f4713Ff889157D5a2930c69e8C6AC61d1BF， tron just adds 41 before address. but tron will not use 41 when transferring asset, '41' is just to show 'T' in TQFPofPMs2y7ht9xgN7vN85g53RWGwHBgF.  If you run 
`tronWeb.address.fromHex('0x9CA16f4713Ff889157D5a2930c69e8C6AC61d1BF')`
you can get base58 format address TQFPofPMs2y7ht9xgN7vN85g53RWGwHBgF.
