### ISSUE TITLE
离线签名

### ISSUE THREAD

**Issue by Mtczf** [tronprotocol/tronweb#197]
您好，最近在研究离线签名时遇到一个问题，根据开发网站中签名说明步骤，新写的离线签名方法，使用示例提供的priKey和hash，生成r、s、v和示例结果一致，但是使用Nile测试网API，在测试TRX转账交易时，使用BroadcastTransaction方法，广播签名后的交易，接口返回信息 "validate signature error 0e7f61ea1768775d441de00ad2240db139a456f9b9e7a3e46de31de2358edfb51978f5d3bff9034fffc789155c2a321b6d405288bb764a717e6121a48efdd0d600 is signed by TPrWjafriXpjwKJG5mNcNYsG8TvYZbjNoZ but it is not contained of permission"。
这个问题困扰一段时间，请帮忙解答下这是什么原因？

**Comment by Benson0224** [comment]
> tronweb离线签名的原理有吗？只能跟踪到调用GetNodeInfo和CreateTransaction这两个API，如何将这两部分数据组合，可以说明下吗？

Please refer to tronweb source code :
https://github.com/tronprotocol/tronweb/issues/197#issuecomment-940892746

you can also find the tronweb API guide from here: https://cn.developers.tron.network/reference#%E7%AD%BE%E7%BD%B2

**Comment by Alexliu007** [comment]
> tronweb离线签名的原理有吗？只能跟踪到调用GetNodeInfo和CreateTransaction这两个API，如何将这两部分数据组合，可以说明下吗？

The tronWeb code is open source and you can find the specific implementation of the sign method.
