### ISSUE TITLE
How to get the hex of the transaction ？

### ISSUE THREAD

**Issue by stefaniepei** [tronprotocol/tronweb#200]
`const tradeobj = await tronWeb.transactionBuilder.sendTrx('TNo9e8MWQpGVqdyySxLSTw3gjgFQWE3vfg', 100,'TM2TmqauSEiRf16CyFgzHV2BVxBejY9iyR',1);  `
`const signedtxn = await tronWeb.trx.sign(tradeobj, privateKey);`
`console.log(signedtxn);`

`
{ visible: false,
  txID:
   'cbf76171dcf5f8fe00b4911a1a6cc4d2a4448e3348f44d240ca20af06025d0f2',
  raw_data:
   { contract: [ [Object] ],
     ref_block_bytes: '6394',
     ref_block_hash: '8ad966a9b0b6a5d1',
     expiration: 1580983512000,
     timestamp: 1580983453441 },
  raw_data_hex:   '0a02639422088ad966a9b0b6a5d140c0d7d7cf812e5a65080112610a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412300a15417946f66d0fc67924da0ac9936183ab3b07c811261215418cb2ab880d4fa7b33c9645a2276dc9b192902e2d186470818ed4cf812e',
  signature:
   [ '47b1f77b3e30cfbbfa41d795dd34475865240617dd1c5a7bad526f5fd89e52cd057c80b665cc2431efab53520e2b1b92a0425033baee915df858ca1c588b0a1800' ] }
`

signedtxn.raw_data_hex is not hex of the transaction, Cannot broadcast at this address https://nile.tronscan.org/#/tools/transaction-viewer

**Comment by summertanh** [comment]
Hi, the page on tronscan is for broadcasting transcation hex, but tronWeb does not provider any method to generate transaction hex string, you could use wallet-client to generate it. 
And if you want to broadcast the transaction above, you can use tronWeb.trx.sendRawTransaction(signedtxn).
