### ISSUE TITLE
How do I close tronWeb connection?

### ISSUE THREAD

**Issue by pedrohba1** [tronprotocol/tronweb#201]
When I run jest tests with tronWeb, I get the following error:

```js
Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      2 | const TronWeb = require('tronweb');
      3 |
    > 4 | export let tronWeb = new TronWeb({
```

That's because tronWeb does not close it's connection when the application ends. Is there a way to close connection on tronWeb?

**Comment by summertanh** [comment]
It looks like you use tronWeb in node env, you install tronWeb in your project. Tronweb is just a instance created in the project, there is no way to disconnect it , but you could set it as null when the application ends.

**Comment by pedrohba1** [comment]
I will try that. 
Thing is, I think there should be a way to disconnect it.
Web3 has something like that:
https://stackoverflow.com/questions/50632114/web3-websocket-connection-prevents-node-process-from-exiting


It goes like this:
```js
web3.currentProvider.connection.close()

 ```

**Comment by summertanh** [comment]
Thanks for you advice, we will plan to do it.

**Comment by sharifzadesina** [comment]
@summertanh Any workaround for this?
