### ISSUE TITLE
What is the private key in the TronWeb constructor?

### ISSUE THREAD

**Issue by idoor88** [tronprotocol/tronweb#202]
Hi all, I have a question, with TronWeb library, in order to instantiate a TronWeb object, I need to pass in the private key, as following, since I like to use the code to create a wallet, which will generate a private key for the wallet, so why I need to pass in a private key? where to get it?

const tronWeb = new TronWeb({ fullHost: trongrid_url, headers: { "TRON-PRO-API-KEY": 'your api key' }, privateKey: 'your private key' })

Thanks in advance!!

**Comment by summertanh** [comment]
Hi,
If you want to use the account created by the privateKey in the constructor, such as in node env, you need to pass the priviteKey when creating tronweb instance. However, in the DAPP, you can use the tronWeb instance injected by TronLink extension or TronLink App, which you do not need to create an account or tronWeb instance by youself, accout is managed in the wallets.

**Comment by idoor88** [comment]
I just want to create a new tron wallet for my users, so I do not have private key to pass into the constructor, I need to still instantiate the tronWeb object via new TronWeb, then use tronWeb.createAccount() to create a wallet.

Is there a TronWeb constructor which does not need to pass in private key?
Thanks

**Comment by summertanh** [comment]
Hi, 
Yes, you can instantiate the tronWeb object first without any privateVate Key, you only need pass the fulleNode url. And then use tronWeb.createAccout() which you will get a privateKey from the result. Last you could use tronWeb.setPrivateKey('priKey') to set the accout in tronWeb object you just created. 
`const tronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io'
});

const account = tronWeb.createAccout();

tronWeb.setPrivateKey(accout.privateKey);`

After using the 3 steps above, you could get the same account in on tronWeb object.
