### ISSUE TITLE
ERROR: Contract Migrations has not been deployed on the network.

### ISSUE THREAD

**Issue by jilongcui** [tronprotocol/tronweb#207]
When I deploy two contracts in one migration script at Shasta test network, It will report follow error:
`ERROR: Contract Migrations has not been deployed on the network.
For more details, check the transaction at:
https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=d7759c54351f046ca10c99ea6b4ca26af812fd6bc9ae2ec7f66edb66d0a0c2c2
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.`
my init migration script as:
`if (network == "shasta") {
  await deployer.deploy(ERC20Contract);
  await deployer.deploy(ERC721Contract);
  await sleep(5000);
  let erc20 = await ERC20Contract.deployed();
  console.log(erc20.address);
  let pool = await ERC721Contract.deployed();
  console.log(erc721.address);
}`

**Comment by summertanh** [comment]
Hi，could you please offer the txID when you deployed the contract?

**Comment by jilongcui** [comment]
https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=d7759c54351f046ca10c99ea6b4ca26af812fd6bc9ae2ec7f66edb66d0a0c2c2

**Comment by summertanh** [comment]
Hi,
we checked the transaction info , the result of the transcation is successful
