### ISSUE TITLE
Please provide a typescript typing and documentation for the tronweb package.

### ISSUE THREAD

**Issue by amhoba** [tronprotocol/tronweb#209]
Thanks afterall for the hard work!
If you could please provide this really useful feature.
I am using console.log to find out what methods tronweb has :(
there is no documentation. If you could please integrate documentation with typescript typings so they will show up in the IDE themselves. (great example is AXIOS package). Thanks.

**Comment by Benson0224** [comment]
You can find `tronweb` related guide here:
https://developers.tron.network/docs/getting-started_new 
https://developers.tron.network/reference/getaccount
