### ISSUE TITLE
关于用地址和abi生成合约实例调用方法问题

### ISSUE THREAD

**Issue by luozygithub** [tronprotocol/tronweb#211]
正常合约和abi生成合约实例 用Method.call() 没问题。但是我用池子地址和对应abi去生成合约实例调用方法会报错。这可能是什么原因

**Comment by summertanh** [comment]
Hi，
Could you please provide your code snippets ?

**Comment by luozygithub** [comment]
![1638366143(1)](https://user-images.githubusercontent.com/31771728/144244879-4be6454f-a86e-4065-b94b-1fed8c7174dc.png)
![1638366162](https://user-images.githubusercontent.com/31771728/144244926-9f04a2b0-0212-43cb-82c2-9d0b7fdcad53.png)

**Comment by luozygithub** [comment]
[[json地址](url)](https://bafkreiavkva7ondbue4mf7n2d77evlu3n5b44voxjke4cgcfsxphqdpa3m.ipfs.dweb.link/)

**Comment by summertanh** [comment]
Hi,
could you please tell us which function you did call, and show the detail error message?

**Comment by luozygithub** [comment]
token0 方法,其他合约调用没问题，就是pair是合约生成的，用合约生成的pair地址和abi求调用方法会失败

**Comment by summertanh** [comment]
Hi, we checked the abi in the json link, the 'outputs' key is wrong in token0 function, it is outputsG, please check it and fix. Then you can call as follows: 
`b=await tronWeb.contract(abi, 'your pair address'); // abi is the json object
result = await b.token0().call({_isConstant: true});
`
