### ISSUE TITLE
No TypeScript definition files

### ISSUE THREAD

**Issue by JonathanTheZero** [tronprotocol/tronweb#213]
I hereby request typing files for tronweb.
There are no TypeScript `*.d.ts` files included in this project and there is also no `@types/tronweb` package on npm, providing those, however, would greatly improve the dev experience of working with tronweb, may it be in JavaScript or TypeScript. 

Code autocompletion would work and a commented version would save a lot of time as one would not need search through the docs on explanations on a specific method/property/whatsoever.

**Comment by summertanh** [comment]
Thanks for your meaningful advice, which is our plan in next stage.

**Comment by ranmocy** [comment]
Do you mind to share the roadmap or the timeline on this?
Typing information is super helpful for developers to develop apps much faster and safer on the Tron network.

**Comment by onejmi** [comment]
Any updates on this?

**Comment by FrameMuse** [comment]
I found this library - https://www.npmjs.com/package/tronweb.types
