### ISSUE TITLE
Discord invite - expired. Try generate unlimited invite.

### ISSUE THREAD

**Issue by username1565** [tronprotocol/tronweb#214]
![image](https://user-images.githubusercontent.com/39200328/145702517-9dfb61d7-ba9a-4a55-a184-586293ac882a.png)
![image](https://user-images.githubusercontent.com/39200328/145702527-2f48c9d5-a1bb-4c0c-b30d-1d74f0845033.png)

**Comment by summertanh** [comment]
hi, sorry for that, we will create a new one soon. And if you have any question, you can open issue here.
