### ISSUE TITLE
class java.security.InvalidParameterException : owner_address isn't set

### ISSUE THREAD

**Issue by luozygithub** [tronprotocol/tronweb#215]
class java.security.InvalidParameterException : owner_address isn't set
这个是因为生成tronWeb 时候没加私钥么，这里我只是调了一个获取授权额度为啥还需要私钥
	const fullNode = new HttpProvider(connectUrl);
		const solidityNode = new HttpProvider(connectUrl);
		const eventServer = new HttpProvider(connectUrl);
		let tronWeb
		tronWeb = new TronWeb(fullNode, solidityNode, eventServer);

**Comment by summertanh** [comment]
Hi，this is as the fullnode http api needs the owner address, you can set a privateKey such as '01' to initiate tronWeb instance.

**Comment by luozygithub** [comment]
像这样？
const fullNode = new HttpProvider(connectUrl);
const solidityNode = new HttpProvider(connectUrl);
const eventServer = new HttpProvider(connectUrl);
let tronWeb
tronWeb = new TronWeb(fullNode, solidityNode, eventServer,'01');

**Comment by summertanh** [comment]
yes, the code above is ok, and you can also initiate tronWeb instance as follows if fullnode, solidity node and evevt server have the same url.
`let tronWeb = new TronWeb({
  fullHost: connectUrl,
  privateKey
});`
