### ISSUE TITLE
sendTRX method not work

### ISSUE THREAD

**Issue by cloud9020locki** [tronprotocol/tronweb#218]
I used sendTRX from https://developers.tron.network/v4.4.0/reference/sendtrx
but it didn't worked at all. can somebody check it! this doc is not updated since 2 years a go.
does Tronweb has same feature like SendTRX, that I can use in my project?
thank's alot.
Here is my code in Nodejs
I already install and import tronweb to my project
---------------------
let TransferResult=await tronWeb.transactionBuilder.sendTrx("TSDHhR7hWB7KT2TtDGwezmrBSaNzwjHE8Z", 1, "TQKGqHmnaecVquNkT2dLC1Mdtvu3hbSyUx");
console.log(TransferResult);

**Comment by vivian-kang** [comment]
This api works well.  It is used to create an unsigned transaction, then you should sign it and broadcast it. please refer to this demo: https://developers.tron.network/reference/sendrawtransaction Thanks.
