### ISSUE TITLE
getUnconfirmedTransactionInfo not working

### ISSUE THREAD

**Issue by cloud9020locki** [tronprotocol/tronweb#219]
Hi, I used tronWeb.trx.getUnconfirmedTransactionInfo(txid);
But it returns this: {}
https://developers.tron.network/v4.4.0/reference/getunconfirmedtransactioninfo
this document is very old, can somebody check it what happened around?
and one question more, How can I check confirmation happened from tx_id that I have??

**Comment by vivian-kang** [comment]
Hi. This api works well, it can get the unconfirmed transaction info by id. 
For confirmed transaction, you can use "getTransactionInfo" to get detailed transaction info: https://developers.tron.network/reference/gettransactioninfo

**Comment by anirudhmakhana** [comment]
@vivian1912 im running in to the same issue right now where getUnconfirmedTransactionInfo returns `{}`
