### ISSUE TITLE
TriggerSmartContract 这个方法可以加消耗多少trx么，类似于调用solidity的value参数

### ISSUE THREAD

**Issue by luozygithub** [tronprotocol/tronweb#221]

**Comment by vivian-kang** [comment]
If contract method is payable, you can use below way to send TRX/TRC10 token to contract:
Add items into JSON of options parameter of triggerSmartContract. https://cn.developers.tron.network/reference/triggersmartcontract 
Send TRX: Add item: callValue
Send TRC10 token: Add: tokenValue, tokenId

**Comment by luozygithub** [comment]
好的谢谢
