### ISSUE TITLE
There is no way to change the parameter limit (size)

### ISSUE THREAD

**Issue by Dimannot** [tronprotocol/tronweb#222]
https://github.com/tronprotocol/tronweb/blob/11d508a702026f51c6b40eb0b3a63ec20c4c907e/src/lib/contract/method.js#L279
https://github.com/tronprotocol/tronweb/blob/11d508a702026f51c6b40eb0b3a63ec20c4c907e/src/lib/contract/method.js#L318
https://github.com/tronprotocol/tronweb/blob/0b37238a180ab2f969afd0abc44dbaa2b4f116b8/src/lib/event.js#L52

### Missing parameter {limit: 50}
```
const contractUSDT = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t';
tronWeb.setAddress(contractUSDT);
let stats = {};
tronWeb.contract().at(contractUSDT)
.then(contract => {
    contract.Transfer().watch({limit: 50}, (err, result) => {
        if(stats[result.block]) {
            stats[result.block]++;
        } else {
            stats[result.block] = 1;
        }
    });
});

setInterval(function () {
    console.log(new Date(), stats);
}, 3000);
```

Example API
https://api.trongrid.io/v1/contracts/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/events?event=Transfer&limit=50

When testing an event with an extended  parameter **size 200**, blocks often do not come. Although the USDT token has Transfer events on the blockchain for the skipped blocks

>   '37121949': 26,
>   '37121950': 45,
>   '37121952': 70,
>   '37121953': 59,
>   '37121954': 36,
>   '37121956': 55,
>   '37121957': 53,
>   '37121958': 33,
>   '37121960': 45

Probably blocks with USDT transactions exceeding 200 transfers can be caught (example block 37121255 218)

**Comment by summertanh** [comment]
Hi,
tronweb doesn't call the API https://api.trongrid.io/v1/contracts/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/events?event=Transfer&limit=50, we just use https://api.trongrid.io/event/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/transfer/?size=50
you can use `size` instead of `limit`.

**Comment by Dimannot** [comment]
This was an example of an API request. In the code itself cannot set size option

**Comment by Dimannot** [comment]
> Hi, tronweb doesn't call the API https://api.trongrid.io/v1/contracts/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/events?event=Transfer&limit=50, we just use https://api.trongrid.io/event/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/transfer/?size=50 you can use `size` instead of `limit`.

You have provided a deprecated version
https://github.com/TRON-US/trongrid/blob/803021396d58d8a2321e6306e05d787018e28db7/README.md

**Comment by summertanh** [comment]
> This was an example of an API request. In the code itself cannot set size option

There is a parameter `filter` in tronweb watch method, you can pass any filter parameters.
And the api will be availabe for a long time after confirmation with the trongrid api server. They have no plan to stop the serve. At the same time, tronweb will plan to update the api to the latest version. if it is done, we will update the develop doc.

**Comment by Dimannot** [comment]
> > This was an example of an API request. In the code itself cannot set size option
> 
> There is a parameter `filter` in tronweb watch method, you can pass any filter parameters. And the api will be availabe for a long time after confirmation with the trongrid api server. They have no plan to stop the serve. At the same time, tronweb will plan to update the api to the latest version. if it is done, we will update the develop doc.

Also does not work through parameter `filters`
```
contract.Transfer().watch({filters: {size: 50}}
contract.Transfer().watch({filters: {limit: 50}}
```

**Comment by Benson0224** [comment]
Seems you have passed wrong parameters:
![image](https://user-images.githubusercontent.com/61768920/149699847-141f7b74-9a1b-4531-9063-27c293dade1d.png)

after changing the `event` to `event_name`, I can see the filter works perfectly. 
https://api.trongrid.io/v1/contracts/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/events?event_name=Transfer&limit=50

For API and parameters detail instructions, please refer to this guide:  https://developers.tron.network/reference/events-by-contract-address

**Comment by Dimannot** [comment]
API works great

In library does not have the ability to use the limit(size) parameter
