### ISSUE TITLE
Broken Demo (tronweb/demo/tron-dapp-react-demo)

### ISSUE THREAD

**Issue by webtree22** [tronprotocol/tronweb#226]
_The better way to understand how to work with TronWeb is go to the demo directory in this repository._

As per instruction on readme file, I downloaded and ran tronweb/demo/tron-dapp-react-demo and ran **npm install** and **npm start**

There are several problems here.

1. Firstly, it can not compile and says there is **no index.html file in public folder**. _(So I created myself one)_
2. Then it says **index.js:55 Uncaught ReferenceError: Home is not defined** _( as I can see no Home component)_

Whats going on ? Is it done deliberately or I am doing something wrong ?

**Comment by summertanh** [comment]
Hi,

**Comment by summertanh** [comment]
Hi,
For some reason the latest code was not merged into master. You can update the code now, run it, and give us feedback if you have any problems.

**Comment by webtree22** [comment]
@summertanh Thanks. Now it is installing, compiling and running fine. Closing the issue.
