### ISSUE TITLE
api-key-limit

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/tronweb#234]
as for [tronweb](https://github.com/tronprotocol/tronweb)

i noticed that all util api are using api-key by http, such as toSUN, toHex....

could you guys provided some node-util  to minus api-key called  times

**Comment by summertanh** [comment]
Hi,
you don't need to set api key in header, api key is necessary when you want to connect with api.trongrid.io server

**Comment by lijianl** [comment]
i am tryung to using my own node

**Comment by summertanh** [comment]
well, you can ignore the api key when calling your own fullnode.
