### ISSUE TITLE
tron-web util

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/tronweb#235]
do you have any node util to convert address from hex to base58 

and convert address from base58 to hex

**Comment by summertanh** [comment]
hex to base58: tronWeb.address.toHex('TKT9et6Z8ik29c8gPNiZTh5b5RzNofG6BB')
base58 to hex: tronWeb.address.fromHex('416801fbfbdf12a210a6a077f879c76691d415b9f4')

**Comment by lijianl** [comment]
i need the util that will not cost api-key times,

local node maybe the best way to solve this

**Comment by Benson0224** [comment]
These 2 are kind of Library Functions, it does not communicate with the node when you are using these 2 functions. 
hex to base58: tronWeb.address.toHex('TKT9et6Z8ik29c8gPNiZTh5b5RzNofG6BB')
base58 to hex: tronWeb.address.fromHex('416801fbfbdf12a210a6a077f879c76691d415b9f4')
