### ISSUE TITLE
status: 503,     statusText: 'Service Temporarily Unavailable',

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/tronweb#237]
url: 'https://api.trongrid.io/wallet/gettransactioninfobyid',
      method: 'post',
      data: '{"value":"6019a561656bd85d89abc95be685f05431ea7939c26b93ebea81a3832f6a4f1d"}'

this api is always 503, could you guys give some tips to solve this

**Comment by summertanh** [comment]
please use get method
https://api.trongrid.io/wallet/gettransactioninfobyid?value=6019a561656bd85d89abc95be685f05431ea7939c26b93ebea81a3832f6a4f1d

**Comment by lijianl** [comment]
service 503 is always there, could you guys give a doc to  avoid this

**Comment by Benson0224** [comment]
503 means you exceeded the TRONGRID request limits.  please optimize your code and reduce the frequency. 

https://developers.tron.network/docs/faq#10how-to-solve-the-error-of-trongrid-503-service-temporarily-unavailable
