### ISSUE TITLE
return []

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/tronweb#238]
get event through api
let evs = await tron.getEventByTransactionID(hash).catch(err => console.error(`tron-event-error,${hash}`,err)); 

the api always return [] when scan transaction,  could you help for this

**Comment by Benson0224** [comment]
please share one transaction hash which you can not get the event, thanks.

**Comment by lijianl** [comment]
350517abf0977260085ad71066061fe2fe1dd3ec3ba47bca7e521b5301496a94

many when scan smart transaction

**Comment by Benson0224** [comment]
I can see the correct event from the trongrid event service. 
https://api.trongrid.io/v1/transactions/350517abf0977260085ad71066061fe2fe1dd3ec3ba47bca7e521b5301496a94/events
