### ISSUE TITLE
How to get block number in the first place after broadcast transaction?

### ISSUE THREAD

**Issue by Taineen** [tronprotocol/tronweb#241]
Hi guys,
     I need help when I test the tron transaction with tronWeb.

first broadcast a transaction with:
tronWeb.transactionBuilder.sendTrx()
tronWeb.trx.sign()
tronWeb.trx.sendRawTransaction()

then I get txid from transaction and I want to get the block number by txid like:
tronWeb.trx.getTransactionInfo(txid)

The PROBLEM is 'getTransactionInfo' cost about 1 min to get the block number,is there any way to get the block number immediately after broadcast transaction? Thanks.

**Comment by Benson0224** [comment]
try this.
https://developers.tron.network/reference/getblockbynumber
