### ISSUE TITLE
Function with tuple[] as argument inside contract got error with TronWeb

### ISSUE THREAD

**Issue by klode82** [tronprotocol/tronweb#244]
I'm working on a Smart Contract, but I've encountered an issue.
In this pastebin there is the Minimal Contract that reproduce the error: [UsersArray Contract](https://pastebin.com/UhWMbQ8w)

This contract is deployed on ShastaNet with this address: ```TQ1aYRBRyhjofitG9KmWUk2tavvhwqXfTE```.

On the webpage I load the contract as below:
```javascript
function testArray(){
    tronWeb.contract().at("TTmSSy3twJr5ttfcV6HUHMkse9edNzCZ9B")
    .then( contract => {
        contract.setUsers([
            ["0x0000000000000000000000000000000000000001",1234], 
            ["0x0000000000000000000000000000000000000002",5678]
        ]).call()
        .then( res => {
            console.log(res);
        });
    });
}
```

but on request of contract() I got the error:
```
TypeError: Cannot read properties of null (reading 'map')
    at Qe.format (pageHook.js:20:138878)
    at Qe.format (pageHook.js:20:138728)
    at pageHook.js:20:147799
    at Array.map (<anonymous>)
    at st.format (pageHook.js:20:147789)
    at pageHook.js:20:153235
    at Array.forEach (<anonymous>)
    at new kt (pageHook.js:20:152959)
    at pageHook.js:12:199401
    at new e (pageHook.js:12:199585)
```

I'm using Chrome/98.0.4758.105, and the extension TronLink ver. 3.26.4

 From the original Contract, if I remove the function proposed on `UsersArray` `setUsers`, the contract works correctly.

**Comment by summertanh** [comment]
hi,
please try to pass the abi by yourself, as the abiv2 on the network is not correct.
try this code to get your contract instance, you can get the correct abi after you compile the contract.
`const contractInstance = await tronWeb.contract(abi, 'TTmSSy3twJr5ttfcV6HUHMkse9edNzCZ9B')`
