### ISSUE TITLE
android 钱包怎么连接波场dapp，发交易通过钱包签名

### ISSUE THREAD

**Issue by WhiteCjy** [tronprotocol/tronweb#255]

**Comment by Benson0224** [comment]
如果是DAPP 开发者， 可以直接使用钱包里已经注入的Tronweb 对象： 参考文档：
https://cn.developers.tron.network/docs/dapp-integrate-with-tronlink-introduction

如果是钱包开发者，需要自己初始化tronweb ， 文档参考：
https://cn.developers.tron.network/docs/dapp-development-tools-tronweb

**Comment by WhiteCjy** [comment]
我想也是要自己初始化tronweb，监听方法。没看到相关注入的资料，第二个文档打不开

**Comment by Benson0224** [comment]
> 我想也是要自己初始化tronweb，监听方法。没看到相关注入的资料，第二个文档打不开

重启一下浏览器 或者 清除一下缓存。 我这里可以正常打开。

**Comment by WhiteCjy** [comment]
是这个文档啊，这个只是注入了，原生端没法监听到交易的，webview加载与dapp交互

**Comment by Benson0224** [comment]
监听交易 这一块可以使用tronweb的事件接口 查询事件： https://developers.tron.network/reference/get-events-by-transaction-id

webview加载与dapp交互 ： 这一块的问题是啥？能具体一点吗？

**Comment by Benson0224** [comment]
Close this issue as no reply for a long time. 
Feel free to re-open it if you still see the issue.
