### ISSUE TITLE
用tronWeb.sgin签名，然后用 trident-java 中的 verify验证错误

### ISSUE THREAD

**Issue by JavaChinaLive** [tronprotocol/tronweb#257]
[https://github.com/tronprotocol/trident/issues/59](url)

**Comment by Benson0224** [comment]
> [https://github.com/tronprotocol/trident/issues/59](url)

Please check the source code here, tronweb will set a header to sign the string. 
https://github.com/tronprotocol/tronweb/blob/master/src/lib/trx.js#L711

**Comment by JavaChinaLive** [comment]
![image](https://user-images.githubusercontent.com/105107212/167362147-721e669c-b33e-4634-a377-b4225d4539c9.png)
@Benson0224

**Comment by JavaChinaLive** [comment]
TRX_MESSAGE_HEADER = '\\x19TRON Signed Message:\n32';
TRX_MESSAGE_HEADER = '\u0019TRON Signed Message:\n32';
Both prefixes have been tried and the signature cannot be verified successfully  @Benson0224

**Comment by Benson0224** [comment]
I would suggest you refer below code, and you will see how tronweb verifies the signature. 
https://github.com/tronprotocol/tronweb/blob/master/src/lib/trx.js#L605 
TRONWEB guide: 
https://cn.developers.tron.network/reference/verifymessage
