### ISSUE TITLE
cannot create contract instance

### ISSUE THREAD

**Issue by xfishernet** [tronprotocol/tronweb#259]
Hi! Cannot create contract instance :-(

"tronweb": "^4.2.0",

https://api.shasta.trongrid.io

await this.tronWeb.contract().at('THu5ESLBFBnKnVk446AE6MigiVzvbX8HZV'); (it's USDT token contract)

I get such an error:

Exception happened ------------------------> Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.6.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.6.2)

**Comment by llwslc** [comment]
I just tried it is ok, can you provide more details?

```
const TronWeb = require('tronweb');

(async () => {
  const tronWeb = new TronWeb({
    fullHost: 'https://api.shasta.trongrid.io',
    eventServer: 'https://api.shasta.trongrid.io',
    privateKey: '01'
  });

  const c = await tronWeb.contract().at('THu5ESLBFBnKnVk446AE6MigiVzvbX8HZV');

  console.log(c);
})();
```
