### ISSUE TITLE
getEventResult got error if using fingerprint parameter

### ISSUE THREAD

**Issue by TimHsu-1** [tronprotocol/tronweb#264]
As the doucument [getEventResult](https://developers.tron.network/reference/geteventresult) says we can put the fingerprint options.

But when we put the fingerprint option were get an error :
`{
    "success": false,
    "error": "Invalid query filter(s)!: [fingerprint does not match current set of params]",
    "statusCode": 400
}`

If change option to `_fingerprint` it works.

**Comment by cubefix** [comment]
Please refer to this document

https://developers.tron.network/reference/geteventresult

**Comment by llwslc** [comment]
Could you provide some more detailed code?

**Comment by TimHsu-1** [comment]
I'm using the Postman to run the test.

This request set the `fingerprint` option will get the error :

```curl --location --request GET 'https://nile.trongrid.io/event/contract/TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj/Transfer?fingerprint=T6atjwJCtWof3oL58g5XFEFhgfWZkMrqCpr6BbqDx24kVDKHQYz57Q6a1oUKda2PEZHNSNE1Mz64vLWfKDwcXnWLm5dSQm&eventName=Transfer&sinceTimestamp=1635767509000&sort=block_timestamp'```

But if change the option to `_fingerprint` will get the result :

```curl --location --request GET 'https://nile.trongrid.io/event/contract/TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj/Transfer?_fingerprint=T6atjwJCtWof3oL58g5XFEFhgfWZkMrqCpr6BbqDx24kVDKHQYz57Q6a1oUKda2PEZHNSNE1Mz64vLWfKDwcXnWLm5dSQm&eventName=Transfer&sinceTimestamp=1635767509000&sort=block_timestamp'```

Maybe can check the [line:122](https://github.com/tronprotocol/tronweb/blob/15543c6835953d2e8bae5aef655f869d57d0582c/src/lib/event.js#L122). Thanks for help.

**Comment by llwslc** [comment]
You can follow these steps to use fingerprint.


```
curl https://api.trongrid.io/event/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/Transfer?sort=block_timestamp
```

Take the value of `_fingerprint` from the returned data, and set it to the next url.

```
https://api.trongrid.io/event/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/Transfer?fingerprint=9mPzvhwtq8uTG3KkJa6hTeawdSUn7rFe4HYN6jrPHqPar9RewmvAbg13GuHbqfedKutHdMzGbNDcMNHcjJ4ATCypQsRUgUAoT&sort=block_timestamp
```

**Comment by TimHsu-1** [comment]
It seems using fingerprint on the mainnet (host : `https://api.trongrid.io` ) works fine.
But using fingerprint on the testnet (host : `https://nile.trongrid.io` ) it will fail.

Nile testnet using fingerprint option, it will fail :
```
https://nile.trongrid.io/event/contract/TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj/Transfer?fingerprint=T6atjwJCtWof3oL58g5XFEFhgfWZkMrqCpr6BbqDx24kVDKHQYz57Q6a1oUKda2PEZHNSNE1Mz64vLWfKDwcXnWLm5dSQm
```

Nile testnet using _fingerprint option, it works :
```
https://nile.trongrid.io/event/contract/TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj/Transfer?_fingerprint=T6atjwJCtWof3oL58g5XFEFhgfWZkMrqCpr6BbqDx24kVDKHQYz57Q6a1oUKda2PEZHNSNE1Mz64vLWfKDwcXnWLm5dSQm
```

**Comment by llwslc** [comment]
The fingerprint field appears in **the last data of the previous query**. After specifying the corresponding field content this time, subsequent data will be returned. If there is no this field in the last data of the query, it means that there is no more data
