### ISSUE TITLE
this is my code my function is not working to connect wallet button is displaying but signature is not coming plz help someone

### ISSUE THREAD

**Issue by HARSHisawesome2** [tronprotocol/tronweb#266]
import React from "react";
import { useState } from "react";
const TronWeb = require("tronweb");

export default Body;
function Body() {
  const [lpLogged, setlpLogged] = useState(true);

  async function getTronWeb() {
    if (window.tronWeb && window.tronWeb.defaultAddress.base58) {
      return window.tronWeb;
    }
    return null;
  }

  let curweb = getTronWeb();
  async function initWindow() {
    if (curweb == null) {
      setlpLogged((lpLogged) => false);
      alert.show("We were unable to find any suitble providder.");
    } else {
      setlpLogged((lpLogged) => true);
    }
  }
  return (
    <div>
      <button onClick={initWindow}> link</button> {lpLogged ? "true" : "false"}
    </div>
  );
}

**Comment by llwslc** [comment]
Please refer to this example.

https://github.com/tronprotocol/tronweb/blob/master/demo/tron-dapp-react-demo/src/stores/network.js#L174

**Comment by HARSHisawesome2** [comment]
where i am wrong in my code @llwslc

**Comment by llwslc** [comment]
Please change to this.

```
let curweb = await getTronWeb();
```

**Comment by HARSHisawesome2** [comment]
oh
