### ISSUE TITLE
Static call

### ISSUE THREAD

**Issue by Gr3it** [tronprotocol/tronweb#271]
Where is anyway to do a static call on a contract funcion that modify the blockchain? So read what would be the transaction output without executing it?

**Comment by llwslc** [comment]
Currently you need to modify the ABI manually, then use the call method.

https://developers.tron.network/reference/contract


We will develop this feature as soon as possible.

**Comment by Gr3it** [comment]
In the case of payable functions, there is no way to do a static call because I can't pass the value amount right?

**Comment by llwslc** [comment]
Amount can be passed.

```js
const abi = [
    {
      inputs: [],
      name: 'testPayable',
      outputs: [
        {
          internalType: 'uint256',
          name: '',
          type: 'uint256'
        }
      ],
      stateMutability: 'view',
      // stateMutability: 'payable',
      type: 'function'
    }
  ];
  const contract = await tronWeb.contract(abi, 'TER...14L');
  const result = await contract.testPayable().call({ _isConstant: true, callValue: 1 });
  console.log(result.toString()); // 1
```
