### ISSUE TITLE
Filter events by indexed parameter

### ISSUE THREAD

**Issue by yuripaoloni** [tronprotocol/tronweb#272]
Hey, 

Is there a way to filter events emitted by a specific contract using the indexed parameter? 

I'm trying to use `getEventsResult` but looking at the [docs](https://developers.tron.network/reference/geteventresult) there doesn't seem to be a property to filter by a specific param.

**Comment by llwslc** [comment]
Sorry, TronWeb cannot filter indexed parameters right now.
