### ISSUE TITLE
Memos added with addUpdateData doesn't show up on tronscan

### ISSUE THREAD

**Issue by murdock9999** [tronprotocol/tronweb#279]
Hi, I'm trying to send trx using tronweb api but after using addUpdateData method to add memo and sign and broadcast the transaction, added memo doesn't show up on tronscan shasta. If I send trx using tronlink, memo shows up. I send the transaction using sendRawTransaction  method. That seems like working because the result has "data" element with hexcoded memo I added to the transaction. Please help. 
Thanks in advance.

**Comment by llwslc** [comment]
Please refer to this use case. Can you provide us with your code.

https://github.com/tronprotocol/tronweb/blob/master/test/lib/transactionBuilder.test.js#L1561

**Comment by murdock9999** [comment]
**CODE:**
`async function sendTRX(amount, address) {

    tronWeb.transactionBuilder.sendTrx(
        address,
        amount
    ).then(transaction => {

        tronWeb.transactionBuilder.addUpdateData(
            transaction,
            "luke"

        ).then(tx => {

            tronWeb.trx.sign(
                tx
            ).then(signed => {

                tronWeb.trx.sendRawTransaction(
                    signed
                ).then(result => {

                    console.log(JSON.stringify(result));

                }
                )

            })

        })

    })

}

sendTRX(1,'TPrtURgGD3cqqi3MHY15AsDYsQy3ogeBWg');`

**RESULT:**

`{
  "result": true,
  "txid": "84e996b70f881af3a48e14869bf4c87428e4f8cb91f752f578d542e4559c0664",
  "transaction": {
    "txID": "84e996b70f881af3a48e14869bf4c87428e4f8cb91f752f578d542e4559c0664",
    "raw_data": {
      "data": "6c756b65",
      "contract": [
        {
          "parameter": {
            "value": {
              "amount": 1,
              "owner_address": "41e68570a74f01cb77c44dbbd93977d7800344eace",
              "to_address": "41985fcc765e42a5fbade70a194bf09c24692a2cec"
            },
            "type_url": "type.googleapis.com/protocol.TransferContract"
          },
          "type": "TransferContract"
        }
      ],
      "ref_block_bytes": "afd3",
      "ref_block_hash": "fb89fbc05cc866b7",
      "expiration": 1661241471000,
      "timestamp": 1661241411947
    },
    "raw_data_hex": "0a02afd32208fb89fbc05cc866b74098e0d4cdac3052046c756b655a65080112610a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412300a1541e68570a74f01cb77c44dbbd93977d7800344eace121541985fcc765e42a5fbade70a194bf09c24692a2cec180170eb92d1cdac30",
    "visible": false,
    "signature": [
      "3454054af19b94737d210464ae127e75d86ece9d7ef25e766a3ca0a536aa623d293e83c69668d6d42a469c0b6387ecf8de3b17c8852c448deba09fdbf8812a6601"
    ]
  }
}
`
**TRONSCAN ADDRESS OF TRANSACTİON:**

https://shasta.tronscan.org/?_ga=2.30760573.398624024.1661241560-845740307.1659959922#/transaction/84e996b70f881af3a48e14869bf4c87428e4f8cb91f752f578d542e4559c0664

**Comment by murdock9999** [comment]
This time I tried the code below, according to API guide of addUpdateData and sendRawTransaction methods. 

`async function sendTRX(amount, address) {

    var transaction = await tronWeb.transactionBuilder.sendTrx(
        address,
        amount
    );


    var updated = await tronWeb.transactionBuilder.addUpdateData(
        transaction,
        "luke"
    );

    var signed = await tronWeb.trx.sign(
        updated
    )

    var result = await tronWeb.trx.sendRawTransaction(
        signed
    )
    console.log(JSON.stringify(result));

}


sendTRX(1, 'TPrtURgGD3cqqi3MHY15AsDYsQy3ogeBWg');`

Still, the memo doesn't show up on tronscan.

RESULT JSON:
`{"result":true,"txid":"c9449eb0842890e9b5a7aaa8979d8e7ca66a45f61068e56ac92f21433c59008a","transaction":{"txID":"c9449eb0842890e9b5a7aaa8979d8e7ca66a45f61068e56ac92f21433c59008a","raw_data":{"data":"6c756b65","contract":[{"parameter":{"value":{"amount":1,"owner_address":"41e68570a74f01cb77c44dbbd93977d7800344eace","to_address":"41985fcc765e42a5fbade70a194bf09c24692a2cec"},"type_url":"type.googleapis.com/protocol.TransferContract"},"type":"TransferContract"}],"ref_block_bytes":"b530","ref_block_hash":"f8878f20d184f98b","expiration":1661246148000,"timestamp":1661246089959},"raw_data_hex":"0a02b5302208f8878f20d184f98b40a09bf2cfac3052046c756b655a65080112610a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412300a1541e68570a74f01cb77c44dbbd93977d7800344eace121541985fcc765e42a5fbade70a194bf09c24692a2cec180170e7d5eecfac30","visible":false,"signature":["b50c390beee220977ba63c320bb2328a91583fc03248f3279c5422cf50a993eea84fa8798f58875b237f4e1776507db3ac5a225c0a21ffec52732157f5d884c001"]}}
`

TRONSCAN LINK:

https://shasta.tronscan.org/?_ga=2.200748652.398624024.1661241560-845740307.1659959922#/transaction/16d8c28a7e6be539d2f4eed176bdeca23cf22d214b01f4cc66f89236a55eb21c

**Comment by llwslc** [comment]
I've got your transaction, and the memo is there. Tronscan should be blocking the memo of this transaction, because it only transfers 0.000001 trx.

```
{
	"ret": [{
		"contractRet": "SUCCESS"
	}],
	"signature": ["b50c390beee220977ba63c320bb2328a91583fc03248f3279c5422cf50a993eea84fa8798f58875b237f4e1776507db3ac5a225c0a21ffec52732157f5d884c001"],
	"txID": "c9449eb0842890e9b5a7aaa8979d8e7ca66a45f61068e56ac92f21433c59008a",
	"raw_data": {
		"data": "6c756b65",
		"contract": [{
			"parameter": {
				"value": {
					"amount": 1,
					"owner_address": "41e68570a74f01cb77c44dbbd93977d7800344eace",
					"to_address": "41985fcc765e42a5fbade70a194bf09c24692a2cec"
				},
				"type_url": "type.googleapis.com/protocol.TransferContract"
			},
			"type": "TransferContract"
		}],
		"ref_block_bytes": "b530",
		"ref_block_hash": "f8878f20d184f98b",
		"expiration": 1661246148000,
		"timestamp": 1661246089959
	},
	"raw_data_hex": "0a02b5302208f8878f20d184f98b40a09bf2cfac3052046c756b655a65080112610a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412300a1541e68570a74f01cb77c44dbbd93977d7800344eace121541985fcc765e42a5fbade70a194bf09c24692a2cec180170e7d5eecfac30"
}
```
