### ISSUE TITLE
watch method looks like it will miss events

### ISSUE THREAD

**Issue by FeiFanLiang** [tronprotocol/tronweb#280]
when use `contract.Transfer().watch()`only return each time 20 events，I tested transferring usdt-trc20 from one of my addresses to another,but not listening.when i switch to use `https://api.trongrid.io/event/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/transfer`,it will catch event.

**Comment by FeiFanLiang** [comment]
So what is the point of this method?

**Comment by llwslc** [comment]
#276 We will fix it in the next release
