### ISSUE TITLE
watch method for listening events on nile returns empty array 

### ISSUE THREAD

**Issue by AMihaylenk0** [tronprotocol/tronweb#282]
Encountered with a problem when listening events from contract with tronweb on nile testnet

```
const contract = await (window as any).tronWeb.contract().at(TRON_CONTRACT_ADDRESS_TESTNET)
contract.GameCreated().watch((err: any, event: any) => {
    if (err) {
      return console.error('Error with "method" event:', err)
    }
    if (event) {
      console.log(event, "GameCreated events")
    }
  })
```
watch makes requests in intervals to https://event.nileex.io/event/contract for latest block but always return empty array, however on 
https://nile.tronscan.org/#/contract/TRON_CONTRACT_ADDRESS_TESTNET/events these events are there
https://event.nileex.io/event/contract/TRON_CONTRACT_ADDRESS_TESTNET/GameCreated/29660336/size=20&page=1
where 29660336 - blockNumber

**Comment by AMihaylenk0** [comment]
Looks like its working now 🙏

**Comment by nickmura** [comment]
How did you solve this?
