### ISSUE TITLE
Improve supply chain security by using new cryptography libraries

### ISSUE THREAD

**Issue by paulmillr** [tronprotocol/tronweb#286]
You are using `"elliptic": "^6.5.4"`. It can be replaced by `@noble/secp256k1`, which had independent security audit and uses 0 dependencies. As a comparison, elliptic had 2 security vulnerabilities (CVEs) and uses non-native bigint code, which increases bundle size by a big amount.

Ethers.js you're using will switch to noble in the next v6, so it could be beneficial to also do it.

**Comment by justacoding** [comment]
Thank you for your attention to this repo, we will follow up with relevant assessments and improvements.

**Comment by summertanh** [comment]
Thank you for your attention to this repo, we will follow up with relevant assessments and improvements

**Comment by paulmillr** [comment]
@summertanh what's the decision?
