### ISSUE TITLE
First request to nowhere

### ISSUE THREAD

**Issue by anarchomeritocrat** [tronprotocol/tronweb#287]
Hi all!
Explain please a sense of that line
https://github.com/tronprotocol/tronweb/blob/2d3b0d13c27dcfe9a93e667dd0c1523918f497a4/src/lib/contract/method.js#L381
In fact, this skips the first event on the contract method, which is why it is necessary to artificially send one transaction every time an application using tronWeb for transaction monitoring is restarted, just for as do not to miss a single real user transaction. Is this line really needed here?

**Comment by summertanh** [comment]
As setInterval function will be  executed after 3 seconds at the first time when users use watch method, adding this code here to ensure that the user can obtain the whole event data.
