### ISSUE TITLE
v3.2.7 bugs of call type 'address[][]'

### ISSUE THREAD

**Issue by boy-good** [tronprotocol/tronweb#288]
ERROR: expected array value (argument=null,value="",code="INVALID_ARGUMENT").

**Comment by boy-good** [comment]
example: 
contract: TB6sPc4aJhGAG7NjaCWcpikxoEE1LHczDg
function: callGetAmountsOut
router_address: 'TKzxdSv2FZKQrEqkKVgp5DcwEXBEKMg2Ax'
paths_address:[["0xb4a428ab7092c2f1395f376ce297033b3bb446c1","0x891cdb91d149f23b1a45d9c5ca78a88d0cb44c18"]]
amountIn: '11964000000'

**Comment by summertanh** [comment]
please update to the latest stable version 4.3.0, and try to all the contract which will be successful

**Comment by boy-good** [comment]
> please update to the latest stable version 4.3.0, and try to all the contract which will be successful

got it, thanks!
