### ISSUE TITLE
api time out 

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/tronweb#303]
```js
const tronWeb = new TronWeb(fullNode, solidityNode, eventServer, privateKey)
tronWeb.setHeader({ "TRON-PRO-API-KEY": 'your api key' });
```

the timeout error always happened, how to set timeout config when init TronWeb

**Comment by summertanh** [comment]
Could you please show the timeout host server or DNS ? There is no timeout config for TronWeb initiation at present.
