### ISSUE TITLE
Is it supported to modify the owner of the contract?

### ISSUE THREAD

**Issue by zhwir** [tronprotocol/tronweb#305]
Is it supported to modify the owner of the contract?
I deployed a contract with account A, and I want to authorize account B to have permission to call tronWeb.transactionBuilder.updateSetting in the future.

**Comment by llwslc** [comment]
Please refer to this document.

https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable-transferOwnership-address-

**Comment by zhwir** [comment]
Thanks. I know this method can transfer CUSTOM permissions of the contract, but updateSetting(userFeePercentage) is a NATIVE function of TVM and it seems that it cannot transfer its ownership?

**Comment by llwslc** [comment]
https://developers.tron.network/reference/wallet-updatesetting

Yes,`updatesetting` is used to modify the`consume_user_resource_percent` value of the contract.
