### ISSUE TITLE
signMessageV2 is not exist in tronWeb.trx

### ISSUE THREAD

**Issue by aimazingfeed** [tronprotocol/tronweb#306]
I've tried to sign message with signMessageV2 and can't find the method in  window.tronWeb.trx. I am using 4.4.0 version of the package, which is supporting it.
![image](https://user-images.githubusercontent.com/46224499/200675646-063828a6-e057-49ba-af66-84572f8e77f3.png)

**Comment by zhuqingguang** [comment]
Maybe the `window.tronWeb` is not v4.4.

If you use TronLink chrome extension , then the `window.tronWeb` object is the same as `window.tronLink.tronWeb`. Its version is different from `import tronWeb from 'tronWeb'`. 

You can use `tronWeb.version` to confirm the version is 4.4 or not.

**Comment by aimazingfeed** [comment]
Ok, I've just checked the version of the tronWeb with tronWeb.version and you were almost right - it's 4.1.0
The 4.1.0 version always returns from window.tronWeb and imported tronWeb is 4.4.0. But i still can't get it, how i need to use imported tronWeb from 'tronWeb'

**Comment by zhuqingguang** [comment]
It seems that the TronLink has an old version tronWeb.

Please use the following code to sign a message
```
var str = "helloworld"; 
var HexStr = tronWeb.toHex(str);
var signedStr = await tronWeb.trx.sign(HexStr, privateKey);
console.log(signedStr)
```

**Comment by aimazingfeed** [comment]
I see, so is it correct to use sign method for signing authorization message. There was attention in docs, that this method is not safety to use it for authorization.
And what if I need to use not hexadecimal string?

**Comment by zhuqingguang** [comment]
Yes, you can use `trx.sign` to sign a message or a transaction.

TronLink extension will set a `tronWeb` instance on `window` and use your private key, so if you use `window.tronWeb.trx.sign`, privateKey can be omitted.

But if you use a tronWeb instance from npm pakcage, you must provide a privateKey as tronWeb doesn't know what privateKey is. It's unsafe if you write  your privateKey into code.

**Comment by aimazingfeed** [comment]
Oh, okey, thanks
