### ISSUE TITLE
Make a SIMPLE example

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#308]
In the README, the first line of code does not work:

<img width="1424" alt="Screenshot 2022-11-11 at 09 52 11" src="https://user-images.githubusercontent.com/382183/201365260-f93589ed-bbf4-4368-872a-3a918905ecab.png">

<img width="1424" alt="Screenshot 2022-11-11 at 09 52 14" src="https://user-images.githubusercontent.com/382183/201365277-a21f71e6-599a-40af-bc06-b37f3332eab8.png">

---

Documentation recommends to go to demos folder. Inside the demos folder are very complicated setups like using React. And I don't even see how to get started.

---

For Ethereum, our competitor, this is how easy it is to get started:

<img width="901" alt="Screenshot 2022-11-11 at 09 53 33" src="https://user-images.githubusercontent.com/382183/201365535-6afbb995-00c5-41ff-977d-bc273d109207.png">

---

I'm looking for something that is easier than the Ethereum experience.

**Comment by summertanh** [comment]
Hi, thanks for you good advice, we will optimize the docs. Now I think you need the code as follows if you want to use the  tronWeb instance injected by TronLink extension.  You can add the following code in you 'script' tag in html file. 
After you get the injected tronWeb instance you can trigger a smart contract. 

      let injectedTronWeb = null;

      window.addEventListener(
        'tronLink#initialized',
        async () => {
          console.log(123);
          // @ts-ignore
          const tronLink = window.tronLink;
          if (!tronLink) {
            console.log('Please install TronLink-Extension!');
            return;
          }
          if (tronLink.ready) {
            injectedTronWeb = tronLink.tronWeb;
          } else {
            const res = await tronLink.request({ method: 'tron_requestAccounts' });
            // console.log(res);
            if (res.code === 200) {
              injectedTronWeb = tronLink.tronWeb;
              console.log('tronWeb', tronWeb);
              return;
            }
          }
        },
        {
          once: true
        }
      );
