### ISSUE TITLE
Requirement to use setAddress is undocumented

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#309]
Currently, using TronWeb to call a contract fails with

> owner_address isn't set

This needs to be corrected with `setAddress` as per 

https://github.com/tronprotocol/tronweb/issues/90

---

However this requirement is undocumented. This should be documented in API and developer documents.

**Comment by summertanh** [comment]
Hi, thanks for your advice, we will update it in next version. Now you can refer issue [#307](https://github.com/tronprotocol/tronweb/issues/307)
