### ISSUE TITLE
wallet_switchChain

### ISSUE THREAD

**Issue by aimazingfeed** [tronprotocol/tronweb#310]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/46224499/201402982-b5cbadec-2016-4dd1-93c7-e8585ff417b8.png">
Is it possible to switch current wallet chain as in the image (example for MetaMask)? I need to connect to the Shasta testnet always, and if chosen network is not Shasta - suggest to user to switch current chain to the Shasta. 
I've tried to find requests RPC-methods, but everything is without purpose...

**Comment by summertanh** [comment]
[The TIP3326](https://github.com/tronprotocol/tips/blob/master/tip-3326.md) is in discuss now,  TronLink will support it once issued. Now you could listen [TronLink event](https://developers.tron.network/docs/tronlink-events). 

```
window.addEventListener('message', res => {
      if (res.data.message && res.data.message.action == 'setNode') {
         console.log('setNode')
          // do sth 
         window.location.reload();
        return;
      }
    });
```
