### ISSUE TITLE
Core dev chat room

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#312]
Hello team. Is there a place for discussion, not just issues about TronWeb?

Specifically, is there a Discord server/channel, Telegram group, or WeChat group we can catch up? （中英文都可以）

**Comment by ethan1844** [comment]
> Hello team. Is there a place for discussion, not just issues about TronWeb?
> 
> Specifically, is there a Discord server/channel, Telegram group, or WeChat group we can catch up? （中英文都可以）

@fulldecent

**Comment by fulldecent** [comment]
谢谢我已经去那边自我介绍 ：-）
