### ISSUE TITLE
Publish documentation from this repo

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#314]
The best way to keep the product documentation in sync is to:

- [x] Create a /docs/ folder in this repo
- [x] Add all documentation as HTML / MD files (bilingual)
- [ ] Publish using GitHub Pages

As current, the documentation at https://developers.tron.network/reference/tronweb-object is wrong and old. This is hurting people. Instead, this project should publish its own documentation and that other page should be redirected to this project's documentation.

**Comment by start940315** [comment]
We are  currently working on it. Thanks for your advice.

**Comment by summertanh** [comment]
published [here](https://tronweb.network/docu/docs/intro)

**Comment by fulldecent** [comment]
Thank you. Can the URL mentioned above be updated to reference this new canonical documentation?
