### ISSUE TITLE
Document relationship between TronWeb and TronLink

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#315]
Please explain the relationship between TronWeb and TronLink. And include this in the project documentation. (See #314 )

At present it seems that code from this project is copied (how) to TronLink (by who? when?). Clear documentation will help explain which versions are included and the release schedule.

Any app that depends on TronLink's TronWeb is at risk of breaking if it does not understand this release schedule.

**Comment by summertanh** [comment]
We will try to connect with TronLink community to offer a doc  to explain the relationship between TronWeb and TronLink.

**Comment by summertanh** [comment]
[Here](https://tronweb.network/docu/docs/TronWeb%20and%20TronLink%20wallet) is the reference.

**Comment by fulldecent** [comment]
Here it says:

> TronLink wallets import the TronWeb lib and initiate a TronWeb instance and export it to the website

However this does not explain which version of the TronWeb lib is used, who decides which version is used and when new versions are added.
