### ISSUE TITLE
Document supported versions

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/tronweb#316]
Please documented supported versions of this product at https://github.com/tronprotocol/tronweb/security

Are past versions supported? Which?

What about the old versions on CDN?

What about the version copied (#315 ) to TronLink?

Is the a bug bounty? Which versions does that apply to?

**Comment by summertanh** [comment]
Documentation support multi-versions is published [here](https://tronweb.network/docu/docs/intro/).
