### ISSUE TITLE
shouldPollResponse returns false

### ISSUE THREAD

**Issue by IRGC** [tronprotocol/tronweb#323]
```
async function send(address, amount) {
let contractInstance = await tronWeb.contract().at('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t');

let args = {
    callValue: 0,
    shouldPollResponse: true
}
let result = await contractInstance.transfer(address, amount).send(args);

return result;
}
```
with `shouldPollResponse` set to `true` i expect to get the transaction info but it returns only false;
why?

**Comment by IRGC** [comment]
@summertanh

**Comment by zhuqingguang** [comment]
If `shouldPollResponse ` is set to be `true`, tronWeb will fetch result .  If the `transfer` is successful, result will be `true`.
Could you please check your `transfer` is successful or not on tronscan ?

**Comment by IRGC** [comment]
> If `shouldPollResponse ` is set to be `true`, tronWeb will fetch result . If the `transfer` is successful, result will be `true`. Could you please check your `transfer` is successful or not on tronscan ?

transfer was successful, but returned false, i also noticed, it keep on waiting for several seconds until txn gets like 20 confirmations then immediately gives false as result?

return type of this function is boolean ?  i thought it would give transaction object that includes txid,etc 

i tested again today it returns `false` only just after txn gets 20 confirmations until then it just waits/hangs.

**Comment by zhuqingguang** [comment]
I have tried your code on the Nile test network and the result is `true`:
![image](https://user-images.githubusercontent.com/24694223/205441043-345c7325-d06b-49e6-811c-8bc0adab8b0e.png)

If  `shouldPollResponse` is `true`, tronWeb will fetch the result every 3s and the promise will pending until the transaction is confirmed.

Once the http request has get result, the promise will be resolved and return `true`:
![image](https://user-images.githubusercontent.com/24694223/205441869-b42f0192-a54b-4e65-ac03-e3470c600ec5.png)

Could you please confirm that if your process is Ok ?

**Comment by IRGC** [comment]
oh,
i directly checked api with transaction hash/id
`https://api.trongrid.io/wallet/gettransactioninfobyid?value=6ec42e59b8ae5de8de92b85f12c6ffcd6b34b01586a63e888f044d6be9243db4`

`"contractResult": ["0000000000000000000000000000000000000000000000000000000000000000"]`
is it normal for USDT contract to return 000000000000000000000000000 on success?
in the result it shows `"result": "SUCCESS"`

**Comment by IRGC** [comment]
@zhuqingguang thanks for the help.
i found that, i had to add `rawResponse: true` to args to get full result. 
still no idea why the usdt contract result is `0000000000000000000000000000000000000000000000000000000000000000`
