### ISSUE TITLE
Convert TRON HD "0x..." address into "41..." or "T" one?

### ISSUE THREAD

**Issue by ally9335** [tronprotocol/tronweb#334]
Because TRON supports HD address generation, I've generated a HD address:

```
import * as ethers from 'ethers'

const node = ethers.utils.HDNode.fromMnemonic(process.env.MNEMONIC)
const dp = `m/44'/195'/0'/0'`;
const i = 1;
const wallet = node.derivePath(`${dp}/${i}`)
console.log(wallet.address)
```

which will start with `0x` --> `"0xfdsfds.........1234`

How to convert it into a valid **TRON** address now? The one that starts with "41" or "T".

I'd prefer to avoid using additional dependencies if possible.

**Comment by summertanh** [comment]
please use the code as follows:
`TronWeb.address.fromHex('0x...')`

**Comment by ally9335** [comment]
"I'd prefer to avoid using additional dependencies if possible." -- TronWeb is dependency. How to do it without TronWeb?

`TronWeb.createRandom({path: "m/44'/195'/0'/0/0"})` --> what mnemonic will will it use to generate an address?

**Comment by summertanh** [comment]
If you do it without TronWeb, maybe you can copy the code in TronWeb.address.fromHex to your project. However, we suggest you use TronWeb If you need to interact with TRON network. Ethers is not compatible with TRON. TronWeb is a friendly and convenient SDK, similar to ethers and web3js.  [More details is our official website.](https://tronweb.network/).

`TronWeb.createRandom` will generate a random mnemonic phrase, besides it will return the account address and private key in full path `m/44'/195'/0'/0/${i}`.

**Comment by ally9335** [comment]
> However, we suggest you use TronWeb If you need to interact with TRON network. Ethers is not compatible with TRON. TronWeb is a friendly and convenient SDK, similar to ethers and web3js. [More details is our official website.](https://tronweb.network/)

Who "we"?
How can you suggest anything if you're unaware of my requirements and constraints?
