### ISSUE TITLE
When tronweb version with staking 2.0 methods & dynamic energy? (GreatVoyage-v4.7.0)

### ISSUE THREAD

**Issue by DmytroShalaiev** [tronprotocol/tronweb#337]
https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.0

**Comment by summertanh** [comment]
We will publish the new version with staking 2.0 methods & dynamic energy at the end of month. The feature is already in branch[ release/v5.1.0](https://github.com/tronprotocol/tronweb/tree/release/v5.1.0).  You could develop  related feature with  the branch built locally. Once we publish it, you just need to replace the dependency from npm and test it which will just take a short time. Any question, please contact us.

**Comment by DmytroShalaiev** [comment]
Thanks

**Comment by summertanh** [comment]
The new version 5.1.0 with staking 2.0 has been published, please install.
