### ISSUE TITLE
Got issue with dependencies crypto?

### ISSUE THREAD

**Issue by gravestar** [tronprotocol/tronweb#338]
> node_modules\brorand\index.js:21
>   if (this.rand.getBytes)
>                 ^
> 
> TypeError: Cannot read properties of null (reading 'getBytes')

i got this error, and this is my package.json

> "devDependencies": {
>     "@babel/core": "^7.18.13",
>     "@babel/node": "^7.18.10",
>     "@babel/preset-env": "^7.18.10",
>     "cross-env": "^7.0.3",
>     "nodemon": "^2.0.19",
>     "prettier": "^2.7.1"
>   },
>   "dependencies": {
>     "axios": "^1.1.3",
>     "cors": "^2.8.5",
>     "dotenv": "^16.0.1",
>     "express": "^4.18.1",
>     "tronweb": "^5.0.0",
>     "web3": "^1.7.5"
>   }

before it's working cool, but when i tried from scratch, delete node_modules and package-lock.json, and this happens.

**Comment by summertanh** [comment]
could you please show the related package's name and specified version? Or maybe you can only try to delete tronweb directory in node_modules and change tronweb version to `^5.0.0` , then install and start you project.

**Comment by gravestar** [comment]
> could you please show the related package's name and specified version? Or maybe you can only try to delete tronweb directory in node_modules and change tronweb version to `^5.0.0` , then install and start you project.

i posted it above on my first post, that my tronweb already on ^5.0.0 version.

**Comment by start940315** [comment]
Where's your project? I need to checkout it and find the reason which causes this problem.
