### ISSUE TITLE
Local testing returns no logs

### ISSUE THREAD

**Issue by saadjhk** [tronprotocol/tronweb#345]
I have created a few tests using tronobox framework, however, when i run those tests with `tronbox/tre` container, i get empty logs array. Is there something wrong with my setup? I haven't been able to find relevant documentation other than `getEventByTransactionID` which returns and empty array for me

**Comment by start940315** [comment]
Please show us your code.

**Comment by saadjhk** [comment]
```javascript
  it("Token Deployed should be transferrable", async () => {
    const instance = await TRC20Detailed.deployed();
    const transferTx = await instance.transfer(
      TronWeb.address.toHex("TUFthHjib1xALEVxTTDzuP5cLDFaKfLvBn"),
      "1000"
    );

    await wait(1)
    const tx = await tronWeb.trx.getTransaction(transferTx);
    const txInfo = await tronWeb.trx.getTransactionInfo(transferTx);
    console.log(txInfo)
    assert(tx.txID === transferTx)
  });
```
Result:

```bash
{}
    ✓ Token Deployed should be transferrable (1038ms)
```

**Comment by start940315** [comment]
tronWeb.trx.getTransactionInfo has to wait the transaction to be solidity on the chain. Try poll the result like waitChainData in  test/helpers/waitChainData.js
