### ISSUE TITLE
tronweb@5.1.0 >> Can't resolve 'querystring'

### ISSUE THREAD

**Issue by tadpole2077** [tronprotocol/tronweb#350]
Using latest: tronweb@5.1.0   [using NPM 6.14.8, Node 14.15.0, Angular 13.3.0] 
on "NPM start" getting..

ERROR in ./node_modules/tronweb/dist/TronWeb.node.js 2209:14-36
Module not found: Error: Can't resolve 'querystring' in '..ClientApp\node_modules\tronweb\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

Prior version of Angular 12.x 11.x 10.x 9.x , no issue.
Webpack V5 now used in Angular 13.x, resulting in fault.

**Comment by tadpole2077** [comment]
Workaround (requires additional testing)

1)  npm install querystring
Note:  npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

2) amend ClientApp\node_modules\tronweb\webpack.config.js
Add a fallback rule for querystring

resolve: {
        modules: [
           ...
        ],
	fallback: {
	    "querystring": require.resolve("querystring-es3")
	}
    },

**Comment by start940315** [comment]
I guess you are using webpack5. And your solution is right since webpack5 doesn't provide polyfills of default node modules anymore.
