### ISSUE TITLE
Vite: "Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.

### ISSUE THREAD

**Issue by nickmura** [tronprotocol/tronweb#351]
I'm trying to call view functions from a token contract

```js

    import { tronWeb } from '../../state/state';
    
    function 
                let usdd = await tronWeb.contract([usddabi], window.tronWeb.address.toHex(USDD_Contract)); 
                let balanceOf = await usdd.totalSupply().call();
```

![image](https://user-images.githubusercontent.com/92566574/227694155-cce6e35f-bb83-41e2-afc6-6e5dd7cacfe9.png)

[Vite](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility) tells me to notify report the error to the maintainers of the library

**Comment by start940315** [comment]
You should go to page https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility and polyfill the lib in your vite config file.

**Comment by nickmura** [comment]
> 

What are you referring to as 'polyfill the lib' ?

**Comment by start940315** [comment]
I mean add buffer module for your code. Like in webpack5, add resolve.fallback.buffer: require.resolve('buffer/') in webpack.config.js. In vite, you can refer to https://stackoverflow.com/questions/70714690/buffer-is-not-defined-in-react-vite
