### ISSUE TITLE
signMessageV2 xxx.match is not a function

### ISSUE THREAD

**Issue by Chi111** [tronprotocol/tronweb#352]
hey , everyone!
When I pass no private key in the argument, privateKey is resolved false, and the function in tronweb executes into the regular expression match method with an error. xxx.is not a function

**Comment by start940315** [comment]
What's your environment? Please show me your code so I can figure out what the problem is.

**Comment by Chi111** [comment]
```javascript
import TronWeb from 'tronweb';

export const SHASTA_BLOCK_CHAIN = 'https://api.shasta.trongrid.io';
export const MAIN_NET = 'https://api.trongrid.io';

const fullNode = MAIN_NET;
const solidityNode = MAIN_NET;
const eventServer = MAIN_NET;
const tronGrid = 'xxxxx';

export const tronWebIns = new TronWeb(fullNode, solidityNode, eventServer);
tronWebIns.setHeader({ 'TRON-PRO-API-KEY': tronGrid });
tronWebIns.setHeader({
  'access-control-allow-origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': '*',
});

const hex = tronWebIns.toHex(msg);
const sign = await tronWebIns.trx.signMessageV2(hex);
``` 




because i didn't pass the privateKey,   Is this a required entry?

TypeError: e2.match is not a function

**Comment by start940315** [comment]
Because you did't pass privateKey in instantiating function, you need to pass privateKey to signMessageV2 as the second argument.

**Comment by Chi111** [comment]
> Because you did't pass privateKey in instantiating function, you need to pass privateKey to signMessageV2 as the second argument.

thank you for your reply！Can i get user's privateKey ？Maybe It’s unsafe。

**Comment by Chi111** [comment]
if i use window.tronWeb.trx.signMessageV2 ?  The private key of the current account in the browser plug-in will be automatically obtained,  Can I understand this?

**Comment by start940315** [comment]
The plugin provided tronweb is instantiated with your priveteKey, so you don't have to provide tronweb.

**Comment by Chi111** [comment]
> The plugin provided tronweb is instantiated with your priveteKey, so you don't have to provide privateKey.
