### ISSUE TITLE
BUSD Token: contract.name is not a function

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/tronweb#356]
I've faced with the issue that `tronweb` library doesn't detect `name()`, `symbol()`, and `decimals()` methods for BUSD Token [TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH](https://tronscan.org/#/token20/TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH)

```js
import TronWeb from 'tronweb';

const tronWeb = new TronWeb({
  fullHost: 'https://api.trongrid.io/',
});
tronWeb.setAddress('TBQDyqoJ2ZJHTRDsrGQasyqBm4nUVLbWee');

try {
  let contract = await tronWeb.contract().at('TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH');
  let result = await contract.name().call();
  console.log('result: ', result);
} catch(error) {
  console.error("trigger smart contract error", error)
}
// trigger smart contract error TypeError: contract.name is not a function
```

Code sample from the documentation: https://developers.tron.network/docs/trc20-contract-interaction#name

* tronweb version: `5.1.0`
* node version: `18.14.2`

For the Tether USD contract API works as expected.

**Comment by Redchar1992** [comment]
BUSD allows only Proxy contracts to be called, ABI for the implementation contract at:
 
[TTtQQxmhZTnpKhdVVJpANpX12vRjc16TxZ](https://tronscan.org/#/contract/TTtQQxmhZTnpKhdVVJpANpX12vRjc16TxZ/code)

**Comment by mahnunchik** [comment]
Is it possible to get implementation contract address by tronweb library?

**Comment by Redchar1992** [comment]
Sorry, the BUSD contract has not been released
