### ISSUE TITLE
How to calculate the fee for transferring TRX or USDT trc20 to another wallet?

### ISSUE THREAD

**Issue by deantek** [tronprotocol/tronweb#360]
I read this thread https://github.com/tronprotocol/java-tron/issues/2982 and still don't understand the transparent scheme for calculating the commission, can someone show the simplest example with the calculation? now i'm stuck on the moment with tronweb 

````
 let txFee = await tronWeb.transactionBuilder.triggerConstantContract(
                    'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 
                    functionSelector, 
                    {
                    feeLimit: 100000000,
                    callValue: 0
                   },
                   parameter,
                   address)
````

What needs to be done next to calculate what approximate amount of trx will be required for a successful transaction?

The problem is that when transferring through Trust Wallet, the application asks to sign a transaction, but does not show how much trx is required for this, with ETH it’s much, because it says at once what maximum amount can be spent on the entire transaction. Therefore, I would like to show an approximate calculation on the site, and not in the application

**Comment by summertanh** [comment]
```
// step1: estimateEnergy for the transaction, the passed params is the same as your triggersmartcontract
const energyEstimate = await tronWeb.transactionBuilder.estimateEnergy(
                    'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 
                    functionSelector, 
                    {},
                   parameter,
                   address);
  // step2: get the energy fee unit, this may vary according to TRON network, suggest getting from this API
 const chainParams = await tronWeb.trx.getChainParameters();   
 const energyFee = chainParams.filter(item => item.key==='getEnergyFee')[0].value;
 // step3: get feeLimit as TRX value 
 const feeLimit = tronWeb.fromSun(energyEstimate.energy_required * energyFee);
```

 // note: need to update tronweb lib to v5.1.0 as `tronWeb.transactionBuilder.estimateEnergy` to estimate energy for triggersmartcontract transaction is supported from the version
 
And transfer trx and trc10, they do not need to cost any energy, it just need some bandwidth

**Comment by deantek** [comment]
> const energyEstimate = await tronWeb.transactionBuilder.estimateEnergy(
>                     'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 
>                     functionSelector, 
>                     {},
>                    parameter,
>                    address);
>   // step2: get the energy fee unit, this may vary according to TRON network, suggest getting from this API
>  const chainParams = await tronWeb.trx.getChainParameters();   
>  const energyFee = chainParams.filter(item => item.key==='getEnergyFee')[0].value;
>  // step3: get feeLimit as TRX value 
>  const feeLimit = tronWeb.fromSun(energyEstimate.energy_required * energyFee);

i get this error

````
Uncaught (in promise) class java.security.InvalidParameterException : owner_address isn't set.
````

**Comment by Melekhin** [comment]
Hello!
I have a problem, after call the _estimateEnergy_, I call the method _triggerSmartContract_ in the options of which I set the feeLimit. 
I expect _triggerSmartContract_ to return the object _transaction_, but it ends up returning the same as estimateEnergy

```
      const estimateEnergy = await tronWeb.transactionBuilder.estimateEnergy(addressContractUSDT_Test, functionSelector, options, parameter, addrTRON);
      console.log('estimateEnergy >> ', estimateEnergy);
      const listTokens = await tronWeb.trx.getChainParameters();
      const priceFee = _.find(listTokens, { 'key': 'getEnergyFee' })?.value;
      const feeLimit = estimateEnergy.energy_required * priceFee  || 100000000;
      options.feeLimit = feeLimit;
      const tx = await tronWeb.transactionBuilder.triggerSmartContract(addressContractUSDT_Test, functionSelector, options, parameter, addrTRON);
      console.log('tx >> ', tx);
      
```

>       LOGS: 
>        LOG  estimateEnergy >>  {"energy_required": 15109, "result": {"result": true}}
>        LOG  priceFee >>  420
>        LOG  tx >>  {"energy_required": 15109, "result": {"result": true}}

**Comment by Melekhin** [comment]
> Is the fullnode server your own? EstimateEnergy is supported in java-tron v4.7.0, you should open the config for EstimateEnergy API, which default is unavailable. And by the way owner_address is your account address, not USDT contract address.

Thanks!

**Comment by PVZMF** [comment]
I ran into two problems with energy estimation.
I use tronWeb v5.1.0

`tronWeb.setPrivateKey(hotWallet.privateAddress)
const parameter = [
            {
                type: 'address',
                value: tronWeb.address.toHex(hotWallet.publicAddress)
            },
            {
                type: 'uint256',
                value: 0
            }
        ];
        const functionSelector = "transfer(address,uint256)"

        const transaction = await tronWeb.transactionBuilder.estimateEnergy(
            tronWeb.address.toHex(contractAddress),
            functionSelector,
            { feeLimit: 1_000_000, callValue: 0 },
            parameter)`

1- When I work with the (https://api.trongrid.io), 
I encounter the `This node does not support estimate energy` error, but when I work with the (https://nile.trongrid.io), I do not receive this error.
I don't know, how to enable EstimateEnergy and supportConstant in the node configuration

2- On the (https://nile.trongrid.io), when I set the value to zero, everything is correct, but when I set another value like 10000, I encounter this error (REVERT opcode executed)
