### ISSUE TITLE
FAILED -TRANSACTION REVERT> Issue

### ISSUE THREAD

**Issue by muhammederenaslan** [tronprotocol/tronweb#362]
Hello i am trying to make a function that transfer usdt on trc20.So this is my code:
const TronWeb = require('tronweb');

// Create a TRON instance
const tronWeb = new TronWeb({
  fullHost: 'https://api.trongrid.io', // Use the TRON full node URL
});

// Function to send USDT TRC20 tokens
async function sendUsdt(addressTo, amount, privateKey, fee) {
  try {
    const amountSun = tronWeb.toSun(amount * 10 ** 6);
    // Convert the amount to SUN

    // Get the contract address of USDT TRC20 token
    const usdtContractAddress = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'; // USDT TRC20 contract address

    // Get the address associated with the private key
    const ownerAddress = tronWeb.address.fromPrivateKey(privateKey);

    // Create the transfer transaction data
    const transferData = await tronWeb.transactionBuilder.triggerSmartContract(
      usdtContractAddress,
      'transfer',
      {
        _to: addressTo,
        _value: amountSun
      },
      [],
      ownerAddress // Set the owner_address parameter
    );
    transferData.transaction.fee = fee; // Set the fee for the transaction

    // Sign the transaction
    const signedTransaction = await tronWeb.trx.sign(
      transferData.transaction,
      privateKey
    );

    // Broadcast the transaction
    const receipt = await tronWeb.trx.sendRawTransaction(
      signedTransaction
    );

    console.log('Transaction receipt:', receipt);
  } catch (error) {
    console.error('Failed to send USDT:', error);
  }
}

// Usage: Call the sendUsdt function with the recipient's address, amount, private key, and fee
const recipientAddress = '';
const amount = 10; // Amount of USDT to send
const privateKey = ''; // Set your private key here
const fee = 100000; // Fee value in SUN

sendUsdt(recipientAddress, amount, privateKey, fee);

So when i run this script i got this output at my terminal:Transaction receipt: {
  result: true,
  txid: '427e928bb3b18ae35ddfb414e7e6ef4156480545455217ed9f4fb8415a88d925',
  transaction: {
    visible: false,
    txID: '427e928bb3b18ae35ddfb414e7e6ef4156480545455217ed9f4fb8415a88d925',
    raw_data: {
      contract: [Array],
      ref_block_bytes: '0b8d',
      ref_block_hash: 'ad302d39364cc947',
      expiration: 1681813767000,
      fee_limit: 150000000,
      timestamp: 1681813709272
    },
    raw_data_hex: '0a020b8d2208ad302d39364cc94740d886a69ff9305a6d081f12690a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412340a15419b55d7623c2fd4ba0ba7e857a2ef04c93b8131b5121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2204b483afd370d8c3a29ff930900180a3c347',
    fee: 100000,
    signature: [
      '483824d9cea524f2e9cb2e2abff4ea60170150b2214490379adb744c46c3e0982fdaf3e90657e7cb6e39e21bd18cc514526d44d9690e17f284f015d37e5af00901'
    ]
  }
}

Then i search the txid and i got this error at tronscan FAILED -TRANSACTION REVERT>.It says i cant trigger the smart contract.I dont know what to do.
https://tronscan.org/#/transaction/427e928bb3b18ae35ddfb414e7e6ef4156480545455217ed9f4fb8415a88d925

**Comment by justacoding** [comment]
please try this when triggersmartcontract,  [here](https://tronweb.network/docu/docs/intro/) is tronweb documentation.
```
// Create the transfer transaction data
const transferData = await tronWeb.transactionBuilder.triggerSmartContract(
  usdtContractAddress,
  'transfer(address,uint256)',
  {
    feeLimit: 20*1e6 // 20trx
  },
  [{type: 'address', value: addressTo},
  {type: 'uint256', value: amount}], // amount is USDT value with 18 decimals, do not transform it to sun unit, they have no relation
  ownerAddress // Set the owner_address parameter
);
```

**Comment by summertanh** [comment]
please try this when triggersmartcontract, [here](https://tronweb.network/docu/docs/intro/) is tronweb documentation.

```
// Create the transfer transaction data
const transferData = await tronWeb.transactionBuilder.triggerSmartContract(
  usdtContractAddress,
  'transfer(address,uint256)',
  {
    feeLimit: 20*1e6 // 20trx
  },
  [{type: 'address', value: addressTo},
  {type: 'uint256', value: amount}], // amount is USDT value with 18 decimals, do not transform it to sun unit, they have no relation
  ownerAddress // Set the owner_address parameter
);
```
