### ISSUE TITLE
Get confirmed balance of TRC20

### ISSUE THREAD

**Issue by samyan** [tronprotocol/tronweb#373]
Is it possible to get the **confirmed** balance of TRC20 from an **address** passing 'latest' as param to **balanceOf** ? I'm trying to do it but seems that param is just ignored.

`trc20Contract.methods.balanceOf(address).call('latest')`

There is anyway to do it?

**Comment by summertanh** [comment]
please try 
`trc20Contract.methods.balanceOf(address).call( {confirmed: true} )`

**Comment by samyan** [comment]
> please try `trc20Contract.methods.balanceOf(address).call( {confirmed: true} )`

You saved my day. Thank you!
