### ISSUE TITLE
Incomplete Transfer Event Emission with Tronweb's contract.Transfer().watch()

### ISSUE THREAD

**Issue by ayzerobug** [tronprotocol/tronweb#375]
I am currently developing a payment solution utilizing USDT-TRC20 on the Tron blockchain using Tronweb. However, I have encountered an issue where the `contract.Transfer().watch()` function does not emit all transfers occurring within the contract. As a result, when comparing the transaction hashes obtained from Tronscan to the existing records, the newly obtained transaction hashes do not appear in the watchlist.

Please provide a solution or guidance on how to ensure that all transfers within the contract are properly emitted and captured by the `contract.Transfer().watch()` function.

Thank you for your attention to this matter.

**Comment by DmytroShalaiev** [comment]
I would not use this method. Open the source it's just a loop with a delay of 3 seconds that calls this.tronWeb.event.getEventsByContractAddress.

**Comment by DmytroShalaiev** [comment]
By default it's use block tag 'latest' in simple loop with delay it can be problem(missing blocks)

**Comment by ayzerobug** [comment]
Yes, i check the source code and notice the watch method is just a loop of the getEvents method at 3 seconds interval while the getEvents get only events of 1 seconds earlier. Hence missing transfers within 2 seconds
