### ISSUE TITLE
could not resolve "@ethersproject/keccak256"

### ISSUE THREAD

**Issue by valpinkman** [tronprotocol/tronweb#385]
We encountered an issue when trying to use `tronweb` in our application.
We use pnpm / esbuild + vite in dev mode, and it seems there is an issue with this file =>

https://github.com/tronprotocol/tronweb/blob/4b131bbcaa94f9d70fffd1dc36577703d42eefa1/src/utils/typedData.js#LL2C1-L7C1

You are importing libraries without declaring them in your `package.json`. The title of the PR is just an example but all `@ethersproject/*` libs do cause problem.

We believe you need to add to your dependencies to make sure it's build with your lib.

**Comment by start940315** [comment]
As ethers@5.7 is a dependency of tronweb, it already includes all packages under namespace @ethersproject. So the problem may encountered when you not install ethers properly.

**Comment by start940315** [comment]
Sorry, you are right. We are always using npm as packager so we didn't encounter this problem, maybe you could try using npm now? This will be fixed in the next version.

**Comment by valpinkman** [comment]
unfortunately we are working on a large monorepo https://githubcom/ledgerhq/ledger-live and with the current setup we cannot easily switch to `npm` :(

Thanks for the fix anyway :)

**Comment by summertanh** [comment]
Hi, we will update it in next version which will be published at the end of this month. Now for your testing, you could install the libs manually with npm or yarn to you node_mudules. If you have any question, please contact us.
