### ISSUE TITLE
Reference error: Window not defined

### ISSUE THREAD

**Issue by wsdt** [tronprotocol/tronweb#393]
Please make the library usable in non-window environments. 

We are trying to integrate tron in our chrome extension.

**Comment by wsdt** [comment]
because of this the library is partially unusable for chrome extensions (e.g. within service workers, manifest v3)

**Comment by start940315** [comment]
https://github.com/tronprotocol/tronweb/issues/377

**Comment by wsdt** [comment]
@start940315  saw that issue,  does it mwan tronweb doesn't work on backends?

**Comment by start940315** [comment]
Currently it doesn't. But you can use 4.x version.
