### ISSUE TITLE
How to calculate fee and transferring USDT trc20 to another wallet?

### ISSUE THREAD

**Issue by Melekhin** [tronprotocol/tronweb#394]
Hello!
I have a problem, after call the _estimateEnergy_, I call the method _triggerSmartContract_ in the options of which I set the feeLimit. 
I expect _triggerSmartContract_ to return the object _transaction_, but it ends up returning the same as estimateEnergy

```
      const estimateEnergy = await tronWeb.transactionBuilder.estimateEnergy(addressContractUSDT_Test, functionSelector, options, parameter, addrTRON);
      console.log('estimateEnergy >> ', estimateEnergy);
      const listTokens = await tronWeb.trx.getChainParameters();
      const priceFee = _.find(listTokens, { 'key': 'getEnergyFee' })?.value;
      const feeLimit = estimateEnergy.energy_required * priceFee  || 100000000;
      options.feeLimit = feeLimit;
      const tx = await tronWeb.transactionBuilder.triggerSmartContract(addressContractUSDT_Test, functionSelector, options, parameter, addrTRON);
      console.log('tx >> ', tx);
      
```

>       LOGS: 
>        LOG  estimateEnergy >>  {"energy_required": 15109, "result": {"result": true}}
>        LOG  priceFee >>  420
>        LOG  tx >>  {"energy_required": 15109, "result": {"result": true}}

**Comment by start940315** [comment]
The first time you call `estimateEnergy`, TronWeb will set estimateEnergy prop to options parameter. Thus, the second time you call `triggerSmartContract`, options still has a estimateEnergy prop which has been set to true. You'll have to use `delete options.estimateEnergy` before you call triggerSmartContract.

**Comment by Melekhin** [comment]
> 

Thanks!

**Comment by Melekhin** [comment]
> The first time you call `estimateEnergy`, TronWeb will set estimateEnergy prop to options parameter. Thus, the second time you call `triggerSmartContract`, options still has a estimateEnergy prop which has been set to true. You'll have to use `delete options.estimateEnergy` before you call triggerSmartContract.

Thanks!
