### ISSUE TITLE
getBlockRange() returns an error for range of 1.

### ISSUE THREAD

**Issue by ehamery** [tronprotocol/tronweb#398]
The `getBlockRange` method returns an error for valid input:
https://github.com/tronprotocol/tronweb/blob/4b131bbcaa94f9d70fffd1dc36577703d42eefa1/src/lib/trx.js#L516-L517
It should be `<` instead of `<=`:
 ```
if (!utils.isInteger(end) || end < start)
     return callback('Invalid end of range provided'); 
```
If `end` is equal to `start`, I expect to get 1 block instead of error.

**Comment by start940315** [comment]
fixed in TronWeb 5.3.1
