### ISSUE TITLE
how calculate bandwidth for sending TRX

### ISSUE THREAD

**Issue by Melekhin** [tronprotocol/tronweb#401]
Hello!

Is there any way to calculate the bandwidth of a TRX transaction before it is sent? 

In order to be able to calculate what the fee will be based on this value.

There is no separate method for calculating this value(bandwidth) or estimating the required amount of badwidth for sending TRX tokens..

**Comment by start940315** [comment]
The bandwidth is calculated based on the transaction raw data length, you can get the length of transaction raw_data to get the estimated bandwidth.
