### ISSUE TITLE
Sign Arbitrary Message

### ISSUE THREAD

**Issue by rahmaniali-ir** [tronprotocol/tronweb#404]
I'm trying to do a similar thing as Keplr's `sign arbitrary message` with tronWeb using typescript in angular

This is how Keplr is doing it as explained [here](https://docs.keplr.app/api/#request-signature-for-arbitrary-message):
```typescript
signArbitrary(
    chainId: string,
    signer: string,
    data: string | Uint8Array
): Promise<StdSignature>;
```

I went through the documentation but I couldn't find it. I'll appreciate any help.

**Comment by start940315** [comment]
Maybe you need trx._signTypedData. You can find example [here](https://github.com/tronprotocol/tronweb/blob/master/test/lib/trx.test.js#L668)
