### ISSUE TITLE
TypeError: tronWeb.transactionBuilder.getDelegatedResourceAccountIndexV2 is not a function

### ISSUE THREAD

**Issue by exfoex** [tronprotocol/tronweb#405]
tx=await tronWeb.transactionBuilder.getDelegatedResourceAccountIndexV2( ad1)

This returns an error:

TypeError: tronWeb.transactionBuilder.getDelegatedResourceAccountIndexV2 is not a function

is this improvement already implemented here?

**Comment by start940315** [comment]
Not yet.

**Comment by start940315** [comment]
Yes. But it's not in transactionBuilder module. You need to try `tronWeb.trx.getDelegatedResourceAccountIndexV2( ad1)`
