### ISSUE TITLE
Add 24 words to fromMnemonic 

### ISSUE THREAD

**Issue by vahidsabet** [tronprotocol/tronweb#407]
Please consider generating HD wallets from 24 words using fromMnemonic.

Is there any substitution for this purpose?

**Comment by start940315** [comment]
It's able to generate HD wallets using 24 words using fromMnemonic. You can just use `tronWeb.fromMnemonic(phrase, path, wordlist)` to create.

**Comment by vahidsabet** [comment]
Dear @start940315,
I mean using both createrandom function and fromMnemonic of created words

**Comment by vahidsabet** [comment]
Also using fromMnemonic with 24 words returned:

code: 'INVALID_ARGUMENT',
argument: 'mnemonic',
value: '[ REDACTED ]'

**Comment by start940315** [comment]
Which version did you use? And can you post your code on this page? Remember to delete the mnemonic phrase.

**Comment by gauravagam** [comment]
I am also facing same error. I am using 5.3.2 version of tronweb.
