### ISSUE TITLE
`options` object is ignored in TransactionBuilder

### ISSUE THREAD

**Issue by eli-lim** [tronprotocol/tronweb#430]
https://github.com/tronprotocol/tronweb/blob/cd30451327302c1133ab47ff709ea904c99d113c/src/lib/transactionBuilder.js#L125

```
...
```

https://github.com/tronprotocol/tronweb/blob/cd30451327302c1133ab47ff709ea904c99d113c/src/lib/transactionBuilder.js#L176-L178

`options` here is not passed to `createTransaction`

**Comment by start940315** [comment]
options parameter in `createTransaction ` is now only used internal. So what do you want to do to use this parameter?

**Comment by eli-lim** [comment]
> options parameter in createTransaction  is now only used internal. So what do you want to do to use this parameter?

E.g. changing the transaction's [`expiration`](https://developers.tron.network/docs/tron-protocol-transaction), instead of using the default of 60 secs

**Comment by start940315** [comment]
You can use `transactionBuilder.extendExpiration` to change it.

**Comment by start940315** [comment]
Tronweb v5.3.2 now support custom block header. You can pass a custom expiration in options `blockHeader` argument.
