### ISSUE TITLE
@noble/secp256k1 package removed from package.json but still required in node build

### ISSUE THREAD

**Issue by george-of-croton** [tronprotocol/tronweb#432]
node build still seems to use the @noble/secp256k1 package. I built it locally and it seems to have @noble/curves/secp256k1.

build on npm registry:
![image](https://github.com/tronprotocol/tronweb/assets/16638647/4f93a3e7-2be1-4cb0-b165-aee87ef3bf5c)
latest build locally:
<img width="731" alt="image" src="https://github.com/tronprotocol/tronweb/assets/16638647/12d755e0-80a1-48f7-9969-012d52de5d66">

is it possible that build has not been pushed to NPM?

**Comment by start940315** [comment]
The master code of git is v5.3.1. And it hasn't been published to npm. So the build result is different.

**Comment by george-of-croton** [comment]
it seems like the current node build on NPM is broken then?

**Comment by tungulin** [comment]
You can use "tronweb": "5.2.0" - without caret . Its working for me

**Comment by start940315** [comment]
You can now using `npm i @noble/secp256k1@1.7.1` to solve this problem. For security reason, I don't recommend using `tronweb@5.2.0` as the [release note](https://tronweb.network/docu/docs/Release%20Note/) posted.
