### ISSUE TITLE
How to activate an account with this module?

### ISSUE THREAD

**Issue by ChrisYP** [tronprotocol/tronweb#435]
Hi there, When I use 
`tronWeb.transactionBuilder.sendTrx(
        tronWeb.address.toHex(toAddress),
        amount * 1000 * 1000,
         tronWeb.defaultAddress.hex
    );`
    method to send to an inactive account, I'll get this error:
class org.tron.core.exception.ContractValidateException : Validate TransferContract error, no OwnerAccount.

How shoud I activate an account use this API instead of use Chrome extension or some wallet like that? thanks!

**Comment by start940315** [comment]
You have to use an existing account to send trx to the account you need to activate. So you need to use the existing private key to instantiate tronweb.

**Comment by ChrisYP** [comment]
> You have to use an existing account to send trx to the account you need to activate. So you need to use the existing private key to instantiate tronweb.

Thanks for your reply. Yes I was using an existing private key but still get this error. I know this is my problem, I will try to find solution, thanks again.
