### ISSUE TITLE
Open DApp by Deeplink not work

### ISSUE THREAD

**Issue by rd-van** [tronprotocol/tronweb#436]
I'm using the Open DApp tutorial to open TronLink mobile app and and launch my DApp link: https://docs.tronlink.org/tronlink-app/deeplink/open-dapp. But I have met some below cases:
1. When I use `action: 'open',` The TronLink mobile app just open some specific link (E.g: 'https://justlend.org/#/home')
2. If the TronLink app not openning, the Deeplink just open the TronLink app, not open the DApp link.

Please help to check these issues, many thanks.

**Comment by svein1010** [comment]
Thanks for participating in the development on Tron. But `tronweb` focus on interacting with Tron blockchain using javascript.
This issue seems to be relative to TronLink app. You can find their community in the footer of [TronLink home page](https://www.tronlink.org/).
