### ISSUE TITLE
contract.send() option `pollTimes`  not working in TronLink

### ISSUE THREAD

**Issue by alienzhangyw** [tronprotocol/tronweb#440]
I'm using TronLink plugin injected tronweb to send smart contract methods:
```ts
this.#tronWeb = window.tron?.tronWeb;

// other code

const contract = await this.#tronWeb.contract(abi, address);
const txID = await contract[method](...args).send({
          shouldPollResponse: true,
          keepTxID: true,
          feeLimit: 2_000_000_000,
          pollTimes: 50,
        });
const info = await this.#tronWeb.trx.getTransaction(txID[0]);
```
But TronLink only pulls the transaction info for 20 times:
![image](https://github.com/tronprotocol/tronweb/assets/58874541/7a698343-6259-4d8a-b153-9d0e52ba603d)

So I may get the `Cannot find result in solidity node` error if the tx takes minutes to be confirmed and I cannot continue the next moves, meanwhile this tx is confirmed later in tron network and I cannot send a same tx again.

**Comment by alienzhangyw** [comment]
I find the reason. The version of TronLink injected tronweb is 5.1.1 while this feature is added in 5.3.0.
Could you please ask the TronLink team to update tronweb version?
I suggest that TronLink need to open a github repo for developers to report issues. The official support telegram group is too inefficient and full of frauds.

**Comment by svein1010** [comment]
This repository focus on the issue of TronWeb. Please contact TronLink team for the feature.
The telegrame group link and email of TronLink team can be found in the footer of [TronLink Homepage](https://www.tronlink.org/) .
