### ISSUE TITLE
check address by method isAddress return false

### ISSUE THREAD

**Issue by tonamson** [tronprotocol/tronweb#441]
I use TronWeb version 5.3.1, and I checked that the address validation method isAddress always returns false when I input any address.

**Comment by start940315** [comment]
What address did you input? The function will return false when your address starts with 0x.

**Comment by tonamson** [comment]
> What address did you input? The function will return false when your address starts with 0x.

TREwjaDa9xhXHqYdPjbQecUUYu7jPokeEP

i use this address

**Comment by start940315** [comment]
As I have tested, the result returned is True. So maybe you need to check if your code went into error somewhere else.

**Comment by tonamson** [comment]
> As I have tested, the result returned is True. So maybe you need to check if your code went into error somewhere else.

i use nuxt and import TronWeb version 5.3.1 can you checkit?

**Comment by start940315** [comment]
Can you just post your code here? Remember to remove privateKey.

**Comment by tonamson** [comment]
I try in nuxt tronweb version is 5.3.2
![image](https://github.com/tronprotocol/tronweb/assets/9658005/0ec35afd-9689-4568-b9af-ead7afc89a64)

**Comment by tonamson** [comment]
I found solution 
```
cp node_modules/tronweb/dist/TronWeb.js ./js/tronweb.js
```
