### ISSUE TITLE
`Assertion failed` during sign

### ISSUE THREAD

**Issue by mattiaferrari02** [tronprotocol/tronweb#446]
I'm creating a transaction using `triggerSmartContract` to send some USDT tokens

```js
const tronInstance = new TronWeb({ fullHost: "https://api.trongrid.io" })
tronInstance.setAddress(myAddress)
const { transaction } = await tronInstance.transactionBuilder.triggerSmartContract(
      contractAddress,
      "transfer(address,uint256)",
      { feeLimit: 10000000000, callValue: 0 },
      [
        { type: "address", value: to },
        { type: "uint256", value: 1000000 }
      ]
    )
    
const signedTx = await tronInstance.trx.sign(
      transaction, 
      hex.encode(privateKey)
    )
```
When i try to sign the `transaction` i get this error:
![Screenshot 2023-11-15 at 15 52 32](https://github.com/tronprotocol/tronweb/assets/65465360/1ddab660-fe9c-4fae-8625-fff0f6b2d10d)

I'm using version `5.3.1` running in browser environment.
I tested the same flow in node environment and it works.
I also tried creating the transaction from the browser environment and passing the obtained transaction to the sign function in node env and it gave out the same `assertion failed`. So it seems to be a problem related to the `triggerSmartContract` function in browser environment

**Comment by svein1010** [comment]
Could you please `console.log` the `transaction` object?  Then we can figure out the problem.

**Comment by svein1010** [comment]
I have tried this method with my own address and it works fine. Please check the address and your privateKey is correct. 
And do you mind providing a demo repo that can reproduct this issue?

**Comment by svein1010** [comment]
`sendToken` is used to transfer TRC10 token but not USDT.
It seems it's not a problem of `triggerSmartContract`. Please check if the address passed to `tronWeb.setAddress()` is matched the privateKey passed to `sign()` with the following code:
```js
const address = tronWeb.address.fromPrivateKey(hex.encode(privateKey));
console.log(address === myAddress)
```

**Comment by svein1010** [comment]
It's a bit hard to location the problem. Perhaps you can check the TronWeb version or others libraries version. Maybe there is something else effect the function.

**Comment by way2ex** [comment]
`triggerSmartContract` logic:
1. encode the parameter according to the `functionSelector` and `parameters`. 
2. send the following object to `https://api.trongrid.io/wallet/triggersmartcontract`:
```json
{
    "contract_address": "41a614f803b6fd780986a42c78ec9c7f77e6ded13c",
    "owner_address": "4166199dd3ae29b71cc71253b21d19bc80bc8f4890",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000000199f9fe51ec358692f84510a003037710cae3e000000000000000000000000000000000000000000000000000000000000f4240",
    "call_value": 0,
    "fee_limit": 10000000000
}
```
Then you will get the `unsigned` transaction.
According to you error screenshot , the problem occurs when encoding the `transaction` json object to protobuf.

Maybe the following steps can help:
1. Compare the returned transaction in node and browser to find the difference between them.
2. Run `tronWeb.utils.transaction.txCheck(unsignedTransaction)` and check the result.

**Comment by svein1010** [comment]
`triggerSmartContract` logic:
1. encode the parameter according to the `functionSelector` and `parameters`. 
2. send the following object to `https://api.trongrid.io/wallet/triggersmartcontract`:
```json
{
    "contract_address": "41a614f803b6fd780986a42c78ec9c7f77e6ded13c",
    "owner_address": "4166199dd3ae29b71cc71253b21d19bc80bc8f4890",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000000199f9fe51ec358692f84510a003037710cae3e000000000000000000000000000000000000000000000000000000000000f4240",
    "call_value": 0,
    "fee_limit": 10000000000
}
```
Then you will get the `unsigned` transaction.
According to you error screenshot , the problem occurs when encoding the `transaction` json object to protobuf.

Maybe the following steps can help:
1. Compare the returned transaction in node and browser to find the difference between them.
2. Run `tronWeb.utils.transaction.txCheck(unsignedTransaction)` and check the result.

**Comment by svein1010** [comment]
The `sign` logic is simple: 
1. check the transaction: `tronWeb.utils.transaction.txCheck(unsignedTransaction)`
2. sign the transaction: `tronWeb.utils.crypto.signTransaction(privateKey, unsignedTransaction)`.

And your error is occurs in `google-protobuf.js`. It seems that it occurs in `txCheck` function.
