### ISSUE TITLE
start method returned from watch is undefined

### ISSUE THREAD

**Issue by ColonelJ** [tronprotocol/tronweb#45]
https://github.com/TRON-US/tronweb/blob/b0a694d4dbcd708a528e32839d8d0e50b8187fe5/src/lib/contract/method.js#L359
Shouldn't this line just be `start: bindListener,` so you can call it later?

**Comment by StarLXL** [comment]
We'll fix this in the next version.

**Comment by summertanh** [comment]
fixed in version v2.10.2
