### ISSUE TITLE
`TronWeb.sha3` result differs from `TronWeb.utils.ethersUtils.keccak256` when hashing hex string

### ISSUE THREAD

**Issue by alienzhangyw** [tronprotocol/tronweb#450]
![image](https://github.com/tronprotocol/tronweb/assets/58874541/b7e93d95-9b0d-461a-9681-4599904b21a3)
You can try it in your browser.

But your Java Trident package's `Hash.sha3` result is the same as `TronWeb.utils.ethersUtils.keccak256`.

Expected for the same hash result for both front-end and back-end.

**Comment by svein1010** [comment]
`tronWeb.sha3()` is used to hash the utf8 string. It will use `Buffer.from(message, 'utf8')` to process the input.
`TronWeb.utils.ethersUtils.keccak256()` only receive hexString or BytesArray.

**Comment by alienzhangyw** [comment]
> `tronWeb.sha3()` is used to hash the utf8 string. It will use `Buffer.from(message, 'utf8')` to process the input. `TronWeb.utils.ethersUtils.keccak256()` only receive hexString or BytesArray.

![image](https://github.com/tronprotocol/tronweb/assets/58874541/db74cda6-b1b4-43d2-a874-037bae9d5f1f)
The document should be clearer like you said.
