### ISSUE TITLE
How to get info about TRC20 transaction

### ISSUE THREAD

**Issue by hedimin** [tronprotocol/tronweb#456]
Hello everyone!

I'm trying to get info about usdt transaction:
`const transactions = await this.tronWeb.trx.getTransactionFromBlock(lastBlockId);`
As a result, this usdt transaction looks like this:
![image](https://github.com/tronprotocol/tronweb/assets/112476754/045884e3-6d01-4a9c-b665-015f01178c71)

I can parse AddressFrom - `this.tronWeb.address.fromHex(transaction.raw_data.contract[0].parameter.value.to_address)`
And contract address - 'this.tronWeb.address.fromHex(transaction.raw_data.contract[0].parameter.value.contract_address)'

How can i get info about AddressTo (receiver of this transaction) and amount of usdt that was send?
Thanks in advance for the help

**Comment by start940315** [comment]
value.data is encoded arguments by encodeParamsV2ByABI. You need to decode using function abi and data by decodeParamsV2ByABI
