### ISSUE TITLE
The error "Uncaught (in promise) ReferenceError: Buffer is not defined"

### ISSUE THREAD

**Issue by CYscared** [tronprotocol/tronweb#473]
The error "Uncaught (in promise) ReferenceError: Buffer is not defined" occurs when trying to retrieve TRC20 token balances using TronWeb in Vue or React.

**Comment by svein1010** [comment]
TronWeb requires `Buffer` to work. You should provide a global `Buffer` variable. You can install [`buffer`](https://www.npmjs.com/package/buffer) and add it to your project.
```js
import { Buffer } from 'buffer/';
globalThis.Buffer = Buffer;
```
