### ISSUE TITLE
Varying outcomes are obtained when estimating energy through different methods.

### ISSUE THREAD

**Issue by AlanDawaCrypto** [tronprotocol/tronweb#475]
There are variations in estimating energy consumption when sending USDT on Shasta. The methods include:
1. Using JSON RPC method eth_estimateGas
2. Utilizing tronWeb.trx.transactionBuilder.estimateEnergy().
3. The actual energy cost when transaction is confirmed

They display distinct values.

**Comment by start940315** [comment]
How did you call those methods and what's the result of them? Please give us more details.
