### ISSUE TITLE
How to predict fee for transfer transaction(TRX & USDT)

### ISSUE THREAD

**Issue by CaCaBlocker** [tronprotocol/tronweb#477]
**I am seeking guidance on determining the approximate fees for transferring TRX and USDT accurately.**

Could you kindly provide a method along with the necessary code?

Thank you.

**Comment by start940315** [comment]
You can get the result from [tronWeb.transactionBuilder.estimateEnergy](https://tronweb.network/docu/docs/API%20List/transactionBuilder/estimateEnergy)
