### ISSUE TITLE
Callback not defined

### ISSUE THREAD

**Issue by the-tchaw** [tronprotocol/tronweb#478]
Dears,

There is an issue in this line below:

https://github.com/tronprotocol/tronweb/blob/cd30451327302c1133ab47ff709ea904c99d113c/src/lib/transactionBuilder.js#L1360C28-L1360C36

`callback` variable is not defined as there is no variable in scope that is called callback. P.s. it is also used some lines before in the same function

**Comment by start940315** [comment]
We've already known this issue. It will be fixed soon.
