### ISSUE TITLE
what is `energy_penalty` returned by triggerConstantContract?

### ISSUE THREAD

**Issue by mattiaferrari02** [tronprotocol/tronweb#483]
What is this data? 
Why isn't typed correctly in version 6.0.0-beta.1? 
How should I use it to calculate the fees for the execution of a smart contract?

**Comment by start940315** [comment]
According to [tron dev documentation](https://developers.tron.network/reference/triggerconstantcontract), this data refer to the penalty energy consumption. We'll typed it in the next beta version.

**Comment by start940315** [comment]
> so that is already counted in energy_used right?

Yes!

**Comment by start940315** [comment]
`energy_penalty` is contained in `energy_used` field. You don't need to concern about the return of `/wallet/getcontractinfo`.
