### ISSUE TITLE
delegateResource from active permsion

### ISSUE THREAD

**Issue by A2DNEW** [tronprotocol/tronweb#485]
Hi
One user add my address and add these permissions:
`Vote, Claim Voting Rewards, TRX Stake (2.0), Delegate Resources, Reclaim Resources.
`
I use this code to send energy from that account to another account:

`await tronweb.transactionBuilder.delegateResource(100000, 'TO_ADDRESS', 'ENERGY', 'OTHER_ADDRESS_THAT_PERMISION_TO_ME', true, 3600);
`
But I get error:
`Private key does not match address in transaction
`
If I change `OTHER_ADDRESS_THAT_PERMISION_TO_ME` to `MY_ADDRESS` i get this error:
`delegateBalance must be less than available FreezeEnergyV2 balance`

**Comment by start940315** [comment]
You need to use tronweb.trx.multiSign to sign this transaction which will need both your privateKey and OTHER_ADDRESS's privateKey.

**Comment by A2DNEW** [comment]
> You need to use tronweb.trx.multiSign to sign this transaction which will need both your privateKey and OTHER_ADDRESS's privateKey.

So, What is the point of permission?!
If I access to OTHER_ADDRESS privatekey, I can delegateResource directly without multiSign

I have a website for sell/buy energy
And users add permission to my address for sell/buy energy from/to these accounts
So, nobody give me privatekey!

**Comment by start940315** [comment]
If you have the permission to delegate other's resource to someone, please try this:
```
const tx = await tronWeb.transactionBuilder.delegateResource(amount, 'TO_ADDRESS', 'ENERGY', 'OTHER_ADDRESS_THAT_PERMISION_TO_ME', true, 3600); 
const stx = await tron.tronWeb.trx.multiSign(tx, 'YOUR_PRIVATEKEY', PERMISSION_ID);
const result = await tronWeb.trx.broadcast(stx);
```

**Comment by A2DNEW** [comment]
> If you have the permission to delegate other's resource to someone, please try this:
> 
> ```
> const tx = await tronWeb.transactionBuilder.delegateResource(amount, 'TO_ADDRESS', 'ENERGY', 'OTHER_ADDRESS_THAT_PERMISION_TO_ME', true, 3600); 
> const stx = await tron.tronWeb.trx.multiSign(tx, 'YOUR_PRIVATEKEY', PERMISSION_ID);
> const result = await tronWeb.trx.broadcast(stx);
> ```

Thank you for your help
How can I calcute amount?
For example, I want to send 32000 energy
How can I convert energy to sun (trx)?
`trx.toSun(32000)` return 320000000 and this amount does not correct
Because after send 320000000 delegate, account received more than 40000 energy, not 32000

**Comment by start940315** [comment]
`energy = trx_amount * total_energy_limit / total_energy_weight`
so
`amount = energy * (total_energy_weight / total_energy_limit)`
You can get total_energy_weight and total_energy_limit through` tronWeb.trx.getAccountResources()`

**Comment by start940315** [comment]
> gidkom

https://tronweb.network/docu/docs/6.0.0-beta.3/API%20List/transactionBuilder/delegateResource

**Comment by gidkom** [comment]
> > gidkom
> 
> https://tronweb.network/docu/docs/6.0.0-beta.3/API%20List/transactionBuilder/delegateResource Here is the doc of `delegateResource`. Remember you need to freeze your balance using `freezeBalanceV2` first.

thank you very much. I got it working
