### ISSUE TITLE
How can I get a public key?

### ISSUE THREAD

**Issue by doob9p** [tronprotocol/tronweb#489]
I've read all the documents and there's no way to get a public key using a private key or a mnemonic.
Is it possible to transfer coins while the user only has a private key?

**Comment by start940315** [comment]
Did you mean get the address of the account? You can use `tronWeb.address.fromPrivateKey`.

**Comment by doob9p** [comment]
> Did you mean get the address of the account? You can use `tronWeb.address.fromPrivateKey`.

`tronWeb.address.fromPrivateKey`
The code returns the wallet address.
All I want is to return the Publik key as a factor for the private key.

**Comment by start940315** [comment]
If you have mnemonic, you can use `TronWeb.fromMnemonic` to get the public key.

**Comment by Spyder15** [comment]
you can go with `tronWeb.address.fromPrivateKey`

**Comment by demka1990** [comment]
как узнать публичный ключ адреса ТРОН
НЕ ПОДСКАЖЕТЕ

**Comment by Spyder15** [comment]
To find the public key of a TRON (TRX) address, you need to follow these steps:

**Make a Transaction** 
**Check on TRONSCAN**

Go to Tronscan and enter the TRON address.

Look at the transaction details to see if the public key is available. It is usually part of the transaction data.
Without a transaction, the public key will remain private.
