### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'Transaction' of 'globalThis.TronWebProto' as it is undefined.

### ISSUE THREAD

**Issue by jeancarrie-kima** [tronprotocol/tronweb#496]
I am having this error after updating tronweb version as `6.0.0-beta.1`.
The app works on the browser which has tronlink wallet installed, but doesn't work on the other browsers without tronlink.

**Comment by jeancarrie-kima** [comment]
![image](https://github.com/tronprotocol/tronweb/assets/118423909/c42d6de2-d8c0-4209-a622-792747e92bde)

**Comment by start940315** [comment]
Can you provide a demo that demonstrate your problem?

**Comment by jeancarrie-kima** [comment]
https://github.com/kima-finance/kima-transaction-widget
Please check this open source project, you can run the example folder using `yarn start`.

**Comment by start940315** [comment]
I see. You use react-scripts, and it didn't load cjs files properly. You need to add the cjs rule manually:
```
{
      test: /\.cjs$/,
      type: 'javascript/auto'
},
```

**Comment by jeancarrie-kima** [comment]
@start940315 Thank you for your support, the issue resolved 👍
