### ISSUE TITLE
Error tronWeb.trx.getBalance(address)

### ISSUE THREAD

**Issue by kandrukKV** [tronprotocol/tronweb#501]
Hi

I'm just getting started with TRON blockchain, but I noticed one problem.
Starting from version 5.3.0 Tronweb gives an error:  "Invalid address provided" if I try to execute this code:

`tronWeb.trx.getBalance('TTSFjEG3Lu9WkHdp4JrWYhbGP6K1REqnGQ').then(result => console.log(result))`

and

`tronWeb.isAddress('TTSFjEG3Lu9WkHdp4JrWYhbGP6K1REqnGQ') // false`

**Comment by start940315** [comment]
As I've tested your code with TronWeb@5.3.0, it outputted the right result. So did you change TronWeb code?

**Comment by start940315** [comment]
Since nuxt don't polyfill crypto, you need to add alias to it in your nuxt.config.ts:
```
alias: {
    'crypto': 'crypto-browserify',
    'buffer': 'buffer/',
    'stream': 'readable-stream',
  },
  app: {
    head: {
      script: [{ children: "window.global ||= window;" }],
    },
  },
```

**Comment by kandrukKV** [comment]
Thank you, you helped me a lot.

I added your changes to the nuxt.config, but I still had this error.

![Снимок экрана 2024-04-15 в 18 18 10](https://github.com/tronprotocol/tronweb/assets/54434777/7339dee7-80c5-4585-acae-ea9d0191a050)

This is the only way I've been able to solve this problem.:

`import { Buffer } from 'buffer';
window.Buffer = Buffer`

**Comment by start940315** [comment]
Yes you have to do this if you want to get trx20 balance, because TronWeb uses `Buffer` internally.

**Comment by kandrukKV** [comment]
Thank you!
