### ISSUE TITLE
[Feature]  Think about separate TronWeb into 2 versions - For NodeJS and For Browser.

### ISSUE THREAD

**Issue by raymondmeg** [tronprotocol/tronweb#502]
as titile

**Comment by start940315** [comment]
Any problem with TronWeb? After upgrade to v6.0.0-beta, we have provided 3 outputs of TronWeb. The esm, the commonjs and umd type for browser. Welcome to try!

**Comment by raymondmeg** [comment]
It's not about "if there's any problem" .  Nodejs is an event driven and IO asynchrony design.    different with the browser.

**Comment by itxtoledo** [comment]
even with funding from Justin Sun they don't update this library, imagine dividing it into two...

**Comment by start940315** [comment]
TronWeb does not use node or browser-specific features and works normally in both node and browsers. The beta version already supports modularity, making it easier to use TronWeb in various environments, which is similar to the popular `ethers` and `web3.js`.

**Comment by start940315** [comment]
> even with funding from Justin Sun they don't update this library, imagine dividing it into two...

We currently support the typescript version, welcome to try the beta version. Please install it as follows:
```bash
npm install tronweb@beta
```
 If you have any new feature advice or questions, please open an issue at any time.
