### ISSUE TITLE
Project don't have stable version for production (axios, @noble/secp256k1)

### ISSUE THREAD

**Issue by boxexchanger** [tronprotocol/tronweb#503]
1) Axios Fixed in 5.3.2 but version unavaliable for production version v5.3.2 Cannot find module @noble/secp256k1 https://github.com/tronprotocol/tronweb/issues/481 Moderate security vulnerability for versions of Axios (https://github.com/tronprotocol/tronweb/issues/472)

We can't use beta version project for production please provide stable version for production.

**Comment by start940315** [comment]
You just only to install `@noble/secp256k1@1.7.1` to solve this problem. 5.x is for production.
```bash
npm install @noble/secp256k1@1.7.1
```
