### ISSUE TITLE
multiSign for Contracts return invalid transaction

### ISSUE THREAD

**Issue by khairul-hotakdev** [tronprotocol/tronweb#506]
```

         const transaction = await tronWeb.transactionBuilder.triggerSmartContract(
            process.env.USDT_CONTRACT_ADDRESS,
            'transfer(address,uint256)',
            options,
            parameters,
            mainWallet,
        );
        console.log(transaction)
        const signedTxn = await tronWeb.trx.multiSign(transaction, mainWallet, usdtPermission.id);
        console.log('signedTxn: ', signedTxn);


```
i guess because tronWeb.trx is primarily for TRX transaction, is there any way for doing multisign for Contracts like USDT?
seems there is no t in documentation for this case?

**Comment by start940315** [comment]
It seems like you have passed the wrong address to `triggerSmartContract `. The fifth parameter is the issuer address, not the private key.

**Comment by khairul-hotakdev** [comment]
okay case closed.

it;s because transaction is not a valid transaction object

instead of ` await tronWeb.trx.multiSign(transaction, mainWallet, usdtPermission.id);`

doing this: `await tronWeb.trx.multiSign(transaction?.transaction, mainWallet, usdtPermission.id);`
