### ISSUE TITLE
Invalid address in TRC20 Token

### ISSUE THREAD

**Issue by arkavinod** [tronprotocol/tronweb#507]
const inputs = [
      {
        type: "address",
        value: receiverAddress,
      },
      {
        type: "uint256",
        value: 5,
      },
    ];
    const tx = await tronWeb.transactionBuilder.triggerSmartContract(
      trc20ContractAddress,
      "transfer(address,uint256)",
      options,
      inputs,
      tronWeb.address.toHex(sourceAddress)
    );
    const results = await tronWeb.trx.sign(tx?.transaction, privateKey);
    console.log("results", results)
    
    if we give receiver address which is not a valid tron address but its able to transfer amount to some other random address, instead of that it should give invalid tron address if its a not a valid tron address

**Comment by start940315** [comment]
What address did you pass? The legality verification of parameter addresses relies on the broadcast interface on the chain.

**Comment by zachariahevans174** [comment]
Any&All

Zachariah M Evans

**Comment by ferdinand026** [comment]
@arkavinod Tron node will verify the correctness of the address. There are two forms of tron addresses, if the address is not a valid address, the API will return the error message: "Invalid address provided".

**Comment by arkavinod** [comment]
@ferdinand026 I have passed this address in the above code "0x3d877bd550376f266c16d1b8da648a39f888eb38", which is not a valid tron address

**Comment by arkavinod** [comment]
> What address did you pass? The legality verification of parameter addresses relies on the broadcast interface on the chain.

Hi I have given this address 0x3d877bd550376f266c16d1b8da648a39f888eb38 and its not a valid tron address but still it got proceed to some random address

**Comment by arkavinod** [comment]
@start940315 Hi I have given this address 0x3d877bd550376f266c16d1b8da648a39f888eb38 and its not a valid tron address but still it got proceed to some random address

**Comment by ferdinand026** [comment]
> @ferdinand026 I have passed this address in the above code "0x3d877bd550376f266c16d1b8da648a39f888eb38", which is not a valid tron address

It is an evm addrass. And adding 41 into the front of it will be the TRON hex format address. and for solidity and contract parameter encoding, the address of TRON address will not include the prefix 41. so it is a valid address.

**Comment by arkavinod** [comment]
So it is not valid tron for the above evm address it is creating new tron address and sending USDT token to that address?,
Here is my case using above code with that address it got transferred to some account, I lost my funds, i checked that adress in tronweb it showing only USDT token, no TRX and it's not activated as it's showing in tronweb, means it not created and don't have any transactions for that, so I assuming it is created a address for tron and it got transferred if there no valid tron with that evm address am I correct?

**Comment by ferdinand026** [comment]
TRON’s account generation algorithm is exactly the same as that of Ethereum, and TVM and EVM are basically fully compatible. so it is allowed to input a 20 bytes of hex format address in the above api.

**Comment by arkavinod** [comment]
Okay, thank you
