### ISSUE TITLE
Error messages determination and handling

### ISSUE THREAD

**Issue by mykhailohordin** [tronprotocol/tronweb#508]
Tronweb Version: "5.1.1"
Node Version: "20.11"

Since [GreatVoyage-v4.7.3(Chilon)](https://github.com/tronprotocol/pm/issues/64) of [tronprotocol/java-tron](https://github.com/tronprotocol/java-tron) with [PR#5426](https://github.com/tronprotocol/java-tron/pull/5426) was released I have faced a problem with the error handling, because some of providers didn`t update the version of [tronprotocol/java-tron](https://github.com/tronprotocol/java-tron) on the nodes.

For example:

**Provider#1** will throw such kind of error:
`frozenBalance must be more than 1TRX` - Before [GreatVoyage-v4.7.3(Chilon)](https://github.com/tronprotocol/pm/issues/64)
While **Provider#2** will throw at the same time:
`frozenBalance must be greater than or equal to 1 TRX` - After [GreatVoyage-v4.7.3(Chilon)](https://github.com/tronprotocol/pm/issues/64)

**Question#1:** Is there any plan to handle such kind of errors and redetermine them to one fixed representation.
**Question#2:** Is there any plan to include possible error messages as an enum inside TypeScript version of TronWeb. It would be great because developers could expect what kind of errors they, possibly, would catch.

[Details](https://github.com/tronprotocol/java-tron/issues/5424) of the [PR#5426](https://github.com/tronprotocol/java-tron/pull/5426) issue.

**Comment by DmytroShalaiev** [comment]
Thanks for reply, I think it will nice for the future integrations and UX
