### ISSUE TITLE
An error occurred while running in nodejs

### ISSUE THREAD

**Issue by merlin-li** [tronprotocol/tronweb#515]
Only one line code:
const TronWeb = require('tronweb');

then run "node index.js"

node:internal/modules/cjs/loader:1292
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xx/Desktop/project/gitproject/trontest/node_modules/@noble/secp256k1/index.js from /Users/xx/Desktop/project/gitproject/trontest/node_modules/tronweb/dist/TronWeb.node.js not supported.
Instead change the require of index.js in /Users/xx/Desktop/project/gitproject/trontest/node_modules/tronweb/dist/TronWeb.node.js to a dynamic import() which is available in all CommonJS modules.
    at /Users/xx/Desktop/project/gitproject/trontest/node_modules/tronweb/dist/TronWeb.node.js:1:296544
    at /Users/xx/Desktop/project/gitproject/trontest/node_modules/tronweb/dist/TronWeb.node.js:1:697113
    at Object.<anonymous> (/Users/xx/Desktop/project/gitproject/trontest/node_modules/tronweb/dist/TronWeb.node.js:1:697142)
    at Object.<anonymous> (/Users/xx/Desktop/project/gitproject/trontest/index.js:1:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.9.0

**Comment by start940315** [comment]
Please install @noble/secp256k1@1.7.1
```
npm install @noble/secp256k1@1.7.1
```
