### ISSUE TITLE
How to proper decode a smart contract input data?

### ISSUE THREAD

**Issue by itxtoledo** [tronprotocol/tronweb#518]
Im trying to listen for all blockchain transactions, i already have done receiving TRX, but im stuck on decode TRC20 transactions from `block.transactions`.

This is my code for decode data from "TriggerSmartContract.data" (from params.tx.raw_data.contract[0].parameter.value.data):

```javascript
          const functionCalled = contract.decodeInput(
            contractEvent.parameter.value.data
          );

          if (functionCalled.name !== "transfer") {
            return null;
          }

          console.log("functionCalled", functionCalled);
          console.log("contractEvent.parameter.value.data", contractEvent.parameter.value.data);
```

And this is the output:

```bash
functionCalled { name: 'transfer', params: [ true ] }
contractEvent.parameter.value.data a9059cbb0000000000000000000000004e1f6e4bc98dd381eb0784c8eae2d50bd40d22a80000000000000000000000000000000000000000000000000000000000989680
functionCalled { name: 'transfer', params: [ true ] }
contractEvent.parameter.value.data a9059cbb000000000000000000000000af0932f8c32a6b9bbbe282d6b5193f74c50dc57300000000000000000000000000000000000000000000000000000000000000068e7780
```

In this example two "transfer" events, two parameters comes wrong, but the second in special has a data more longer than expected, why? And How to proper decode these datas?

**Comment by ferdinand026** [comment]
@itxtoledo [Here](https://developers.tron.network/docs/parameter-encoding-and-decoding#example-of-parameter-decoding-using-javascript) is an example code about how to decode parameters.

**Comment by itxtoledo** [comment]
> @itxtoledo [Here](https://developers.tron.network/docs/parameter-encoding-and-decoding#example-of-parameter-decoding-using-javascript) is an example code about how to decode parameters.

yes but in my example the second data will throw this: "The encoded string is not valid. Its length must be a multiple of 64."

**Comment by start940315** [comment]
Where does `contractEvent.parameter.value.data` come from? And which version of TronWeb did you use?

**Comment by LimLex** [comment]
const ethers = require("ethers")
const abi = new ethers.AbiCoder()

function decode(data) {
  const [address, amount] = abi.decode(
    ["address", "uint256"],
    `0x${data.substring(8)}`
  )
  return { address: `41${address.substr(2).toLowerCase()}`, amount }
}
``

**Comment by LimLex** [comment]
`const ethers = require("ethers")
const abi = new ethers.AbiCoder()

function decode(data) {
  const [address, amount] = abi.decode(
    ["address", "uint256"],
    `0x${data.substring(8)}`
  )
  return { address: `41${address.substr(2).toLowerCase()}`, amount }
}
`
