### ISSUE TITLE
Why types are not exported?!

### ISSUE THREAD

**Issue by sharifzadesina** [tronprotocol/tronweb#520]
Just the title. related to v6.

**Comment by sharifzadesina** [comment]
It is possible to import types like this:

```ts
import type { Transaction as TronTransaction } from "tronweb/lib/esm/types/Transaction.js";
import type { TransferContract, TriggerSmartContract } from "tronweb/lib/esm/types/Contract.js";
import type { Block as TronBlock } from "tronweb/lib/esm/types/APIResponse.js";
```

But when you try to import `ContractType`, because it is not a type, we get an error:

```ts
import { ContractType } from "tronweb/lib/esm/types/Contract.js";
```

**Comment by start940315** [comment]
Because ContractType is an enum type and if you import it without `type` key word, it will generate the import statement in the output file. But we don't add this subpath in our package.json as we did't know that anyone will use this object. We are consider to add this subpath in our next version. For now, you can copy the code in the file and use it.

**Comment by zachariahevans174** [comment]
Thank you. God bless 🙏😇🫡🇺🇸

Zachariah M Evans

**Comment by sharifzadesina** [comment]
@start940315 Of course it is not a type, so it throws an error. please on the next update export types also.

**Comment by Satan-web3** [comment]
Types are exported from version TronWeb v6.0.0-beta.4. Welcome to try:
```bash
npm install tronweb@beta
```

**Comment by sharifzadesina** [comment]
Thank you.

**Comment by studentforcode** [comment]
Hello,
i am using tronweb too , and i am having some erro below .. i need help plz

Node.js v22.14.0
PS E:\tronwallet> node transfer.js
node:internal/modules/run_main:91
  const type = getNearestParentPackageJSONType(mainPath);
               ^

Error: Invalid package config \\?\E:\tronwallet\package.json.
    at shouldUseESMLoader (node:internal/modules/run_main:91:16)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:163:20)
    at node:internal/main/run_main_module:36:49 {
  code: 'ERR_INVALID_PACKAGE_CONFIG'
}

Node.js v22.14.0
PS E:\tronwallet>
