### ISSUE TITLE
Module "crypto" has been externalized for browser compatibility: Vite + React

### ISSUE THREAD

**Issue by theprashantparihar** [tronprotocol/tronweb#531]
Using react with vite, I am able to connect to tronlink but when it comes to fetching balance getting a warning: 'Module "crypto" has been externalized for browser compatibility. Cannot access crypto.createHash in client code' and an error 'Invalid address' 

Tried fixing it by following https://github.com/tronprotocol/tronweb/issues/488, installed the three packages added them in viteconfig but then got this error: 'ReferenceError: global is not defined
at node_modules/randombytes/browser.js' tried adding window.global ||= window; but still the error persists

**Comment by start940315** [comment]
`window.global ||= window` should be added before all code which means you may need to add a script at the beginning of `index.html`.

**Comment by theprashantparihar** [comment]
<img width="252" alt="Screenshot 2024-07-03 at 1 53 43 PM" src="https://github.com/tronprotocol/tronweb/assets/171692355/3bd0840a-3968-46bf-ad56-74b88dded6e9">

This is my folder structure, I tried adding window.global ||= window in main.jsx, but got the error: global is not defined, then installed the global package and defined it in viteConfig, then got another error: process is not defined. Did the same, installed process and defined it in viteConfig. Then got 'Cannot read properties of undefined (reading 'slice')' this error.

**Comment by start940315** [comment]
Add it in your `index.html` file, not in main.jsx.

**Comment by theprashantparihar** [comment]
Done, This is how the index.html looks now
<!doctype html>
<html lang="en">
  <head>
    <script>window.global ||= window;</script>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>


After this got an error 'The file does not exist at "/Users/prashant/Documents/crypto_bridge/crypto_bridge/node_modules/.vite/deps/chunk-YIT4L4ID.js?v=92fa8ba1" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.' 
To solve this I excluded it in viteConfig:
optimizeDeps: {
    exclude: ['chunk-PAC5ASQS'] // Add the problematic dependency here
  }
  
  and now getting 'ReferenceError: process is not defined
    at node_modules/browserify-sign/node_modules/readable-'

**Comment by start940315** [comment]
Can your code work? In most scenarios your code will work. And I don't have your code, don't know what's wrong with it.

**Comment by theprashantparihar** [comment]
It is not working, I have attached my package.json and viteConfig. Do you see anything wrong where?
<img width="1001" alt="Screenshot 2024-07-05 at 9 30 31 PM" src="https://github.com/tronprotocol/tronweb/assets/171692355/3a548c43-8751-41ed-9691-c413ae71a67f">
<img width="687" alt="Screenshot 2024-07-05 at 9 30 42 PM" src="https://github.com/tronprotocol/tronweb/assets/171692355/2d796839-9b87-4842-ad86-514138558247">

 I would really appreciate if we can connect, I will show you the code. @theprashantparihar is my tg username

**Comment by theprashantparihar** [comment]
Update: the issue got fixed by adding below to the index.html: 

<script>
      window.global ||= window;
      window.global.process = {
        browser: true
      };
</script>

Thanks @start940315 really appreciate your help.

**Comment by YarPetru** [comment]
I solved similar problem the way below:
1) install to devDependencies "vite-plugin-node-polyfills": "^0.22.0"
2) udpdate configs:
![image](https://github.com/user-attachments/assets/ed1e1ff5-3a4a-45ad-968b-26e2e7bebd06)

**Comment by ibracciano** [comment]
cette solution marche, Merci à toi pour cette brillante recherche

**Comment by pancho-mtl** [comment]
thanks @YarPetru , work for me!!
