### ISSUE TITLE
Error "Cannot find module '@noble/secp256k1'" keeps appearing

### ISSUE THREAD

**Issue by mayorityz** [tronprotocol/tronweb#533]
"exception":true,"level":"error","message":"uncaughtException: Cannot find module '@noble/secp256k1'

I am using the TronWeb package in my nodejs app, all was fine until today, where i am getting this error in my logs

when i install this package, i get a new error, "error":{"code":"ERR_REQUIRE_ESM"},

**Comment by start940315** [comment]
Please install `@noble/secp256k1@1.7.1` instead.
```
npm install @noble/secp256k1@1.7.1
```
