### ISSUE TITLE
Non-base58 character when i try signing a transaction

### ISSUE THREAD

**Issue by owanemi** [tronprotocol/tronweb#537]
![b9b0e638-cb20-48ed-82d8-6e56118ccb6f](https://github.com/user-attachments/assets/7f7a2063-0eab-470e-9d4b-2abd6ff09c29)

i keep getting this error when i try signing a transaction with a private key generated by tronweb, it hasn't happened before and it just started all of a sudden

**Comment by start940315** [comment]
It seems like you have passed the wrong address to the function call argument. Please recheck it.

**Comment by sandrotbilisi** [comment]
hello, were you able to fix error? cause i have same error
