### ISSUE TITLE
`abi.decodeParams` fails to decode, value exceeds width (20 bytes)

### ISSUE THREAD

**Issue by sharifzadesina** [tronprotocol/tronweb#540]
Hello,

[7e45745226085334dd91ce42a3beb76dcb3b6f164f5ec558a49abac8ba1885a0](https://tronscan.io/#/transaction/7e45745226085334dd91ce42a3beb76dcb3b6f164f5ec558a49abac8ba1885a0) this is a valid USDT transaction, but when I am trying to parse contract method data, I am getting the below error:

```
value exceeds width (20 bytes) (operation="toBeHex", fault="overflow", value=95646081903120159615838154932596471023938966366884, code=NUMERIC_FAULT, version=6.13.1)
    at makeError (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/utils/errors.ts:691:21)
    at assert (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at toBeHex (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/utils/maths.ts:194:9)
    at AddressCoder.decode (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/abi/coders/address.ts:34:27)
    at <anonymous> (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/abi/coders/array.ts:108:31)
    at Array.forEach (<anonymous>)
    at unpack (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/abi/coders/array.ts:86:12)
    at TupleCoder.decode (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/abi/coders/tuple.ts:66:16)
    at AbiCoder.decode (/home/sina/Projects/pouch-js/node_modules/ethers/src.ts/abi/abi-coder.ts:209:22)
    at decodeParams (/home/sina/Projects/pouch-js/test2.ts:22:19) {
  code: 'NUMERIC_FAULT',
  operation: 'toBeHex',
  fault: 'overflow',
  value: 95646081903120159615838154932596471023938966366884n,
  shortMessage: 'value exceeds width (20 bytes)',
  baseType: 'address',
  type: 'address'
}
```

You can try:

```js
import { utils as tronUtils } from "tronweb";

tronUtils.abi.decodeParams([], ["address", "uint256"], 'a9059cbb0000000000000000000000417196a564824974842dd03cde3e3020af201baaa400000000000000000000000000000000000000000000000000000000001e8480', true);
```

It will first throw `TypeError: arg.substr is not a function` but the value of `arg` is the above object I provided.

I am using the latest version, 6.0.0-beta.4. this bug existed in beta.3 also, so it is not because of Ethers.js version update.

**Comment by sharifzadesina** [comment]
This can be related to #4446 and #4427.

**Comment by sharifzadesina** [comment]
Web3 is able to decode the data:

```ts
import { Web3 } from "web3";

const web3 = new Web3('https://mainnet.infura.io/v3/ef48b777be6b4d2bb16a9197685eb698');

var d = web3.eth.abi.decodeParameters(['address', 'uint256'], '0x0000000000000000000000417196a564824974842dd03cde3e3020af201baaa400000000000000000000000000000000000000000000000000000000001e8480');

console.log(d);
```

**Comment by start940315** [comment]
Since Tron address is not the same as ethereum, you have to change the address data in the method data. For your scenario, you need to change the `41` to `00` and then it will decode the right result. See more at [here](https://github.com/tronprotocol/tronweb/issues/464#issuecomment-1856034488)

**Comment by sharifzadesina** [comment]
@start940315 what you said has nothing to do with the issue.
because TRC-20 is compatible with ERC-20, addresses inside it don't contain `41`.
this issue is for some special transactions where the Ethers package fails to decode ABI.
please test using the sample codes I've provided.

**Comment by start940315** [comment]
This is obviously that your abi contains address type data. And currently, TronWeb doesn't convert the Tron address to ethereum address. You have to replace it yourself. As for using web3, it is not in our develop roadmap.

**Comment by sharifzadesina** [comment]
So you provide `decodeAbi` method, but that method doesn't support "address" type data?! So what is the point of having `decodeAbi` while it is not going to support the "address" type?!

**Comment by start940315** [comment]
It supports address type, but you must change the data a little. The decoded result of the address type is Tron address.

**Comment by sharifzadesina** [comment]
@start940315 I understand, I thought the `decodeAbi` util is supposed to do the required changes.

**Comment by norbubb** [comment]
Same error

**Comment by Satan-web3** [comment]
> Same error. I'm not sure of following code has no problem.
> 
> ```js
> const trxId = 'e5cfca75a288a799662a3465616d9d5d3501b2d59b0760f094814b9e30b5130f';
> const result = await tronWeb.trx.getTransaction(trxId);
> 
> const parameterData = result.raw_data.contract[0].parameter.value.data;
> // ex) parameterData = 'a9059cbb000000000000000000000041cf74df913cda36aba624f91f55fae1f51ef05e8a000000000000000000000000000000000000000000000000000000000de34c40';
> 
> const arr = parameterData.split("");
> arr[30] = '0'; // remove '4'
> arr[31] = '0'; // remove '1'
> 
> const decodeResult = decodeParams(['address', 'uint256'], arr.join(''), true);
> // decodedResult =  [
> //  "41cf74df913cda36aba624f91f55fae1f51ef05e8a",
> //  233000000n,
> // ]
> ```
> 
> https://developers.tron.network/docs/parameter-encoding-and-decoding#example-of-parameter-decoding-using-javascript

It has no problem.
