### ISSUE TITLE
TronWeb Is not a constructor

### ISSUE THREAD

**Issue by mayorityz** [tronprotocol/tronweb#542]
Hello,

Everytime i try to create a wallet, i get the error, "TronWeb is not a constructor". The tron version is "tronweb": "^6.0.0-beta.3".

`
const TronWeb = require('tronweb')

const privateKey = crypto.randomBytes(32).toString('hex')

      const tronWeb = new TronWeb({
        fullHost: 'https://api.trongrid.io',
        headers: { 'TRON-PRO-API-KEY': config.scans.tron.api_key },
        privateKey,
      })
      const account = await tronWeb.createAccount()

      console.log('New wallet created:')
      console.log('Address:', account.address.base58)
      console.log('Private Key:', account.privateKey)

      // IMPORTANT: Make sure to securely store the private key!
      console.log(
        'IMPORTANT: Securely store the private key. Never share it with anyone!',
      )

      return account
`

**Comment by start940315** [comment]
We changed default exports to named exports which is started from TronWeb v6. Please use 
```
import { TronWeb } from 'tronweb';
```

**Comment by mayorityz** [comment]
> We changed default exports to named exports which is started from TronWeb v6. Please use 
> 
> ```ts
> 
> import { TronWeb } from 'tronweb';
> 
> ```
> 
> Know more differences from [here](https://tronweb.network/docu/docs/6.0.0-beta.3/Migrating%20from%20v5)

Wow. It's a largely commonjs project, which means refactoring all the code to fit. 

Is it possible to downgrade the package?

**Comment by Kerrypinny** [comment]
Hello @mayorityz 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID TRX07638
Please see the link below to our dedicated support line:
[Tron Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by start940315** [comment]
If you don't have enough time to refactor your code. You can use `TronWeb@v5.3.2` by using following command:
```bash
npm install tronweb@latest
```

**Comment by Satan-web3** [comment]
> If you don't have enough time to refactor your code. You can use `TronWeb@v5.3.2` by using following command:
> 
> ```shell
> npm install tronweb@latest
> ```

As TronWeb v6.0.0 has published, you need to using `npm install tronweb@5.3.2`.
