### ISSUE TITLE
Using API 

### ISSUE THREAD

**Issue by zachariahevans174** [tronprotocol/tronweb#544]
I was looking at the initial way to set up the Tron Node and server. How do I obtain my private key using the API or is it possible to transfer using api without the private key.

**Comment by start940315** [comment]
You must create an account first. An account includes a private key and an address. The method is as below:
```js
const account = TronWeb.createAccount();
```

**Comment by zachariahevans174** [comment]
It already shows my main  and side public keys.

**Comment by Satan-web3** [comment]
Did you mean to obtain the genesis account? It is exists in the No.0 block. You can obtain it by using api below:
```js
tronWeb.trx.getBlockByNumber(0);
```
