### ISSUE TITLE
Tronweb version 5.3.2 doesn't ship with types

### ISSUE THREAD

**Issue by slyofzero** [tronprotocol/tronweb#548]
When doing `import TronWeb from "tronweb";` in my TS project, I get the type error saying that 

```
Try `npm i --save-dev @types/tronweb` if it exists or add a new declaration (.d.ts) file containing `declare module 'tronweb';`
```

`@types/tronweb` doesn't exist on the npm registry and thus working with this package is not possible in TS.

**Comment by Satan-web3** [comment]
Please try out beta version which is refactored by ts. You can install it by following command:
```bash
npm install tronweb@beta
```

**Comment by tranphuocanh0207** [comment]
@Satan-web3 beta version can't listen event ?

**Comment by Satan-web3** [comment]
> @Satan-web3 beta version can't listen event ?

You can now try to listen to it by yourself.

**Comment by daochild** [comment]
> When doing `import TronWeb from "tronweb";` in my TS project, I get the type error saying that
> 
> ```
> Try `npm i --save-dev @types/tronweb` if it exists or add a new declaration (.d.ts) file containing `declare module 'tronweb';`
> ```
> 
> `@types/tronweb` doesn't exist on the npm registry and thus working with this package is not possible in TS.

Use this package
https://www.npmjs.com/package/@daochild/tronweb-typescript/v/1.2.105
