### ISSUE TITLE
The correct address is judged as an invalid address through TronWeb.isAdderss 

### ISSUE THREAD

**Issue by weatherstar** [tronprotocol/tronweb#549]
install from npm
Version: 5.3.2
code:
```
TronWeb.isAddress('TF9yaMo6m6V22HyLXCvcQvN4iEdRbQWrbW')
// false
```

<img width="494" alt="截屏2024-08-22 19 18 05" src="https://github.com/user-attachments/assets/d03758df-1a35-48dd-bde2-82ab58f7f0c5">

**Comment by svein1010** [comment]
Did you provide polyfill for `buffer` and `crypto` ? Tronweb depend on these modules to work.
