### ISSUE TITLE
getTokensIssuedByAddress not finding contact addresses on SunSwap 

### ISSUE THREAD

**Issue by catstersol** [tronprotocol/tronweb#553]
TRON has a lot of new meme tokens on DexScreener.  I am trying to find the tokenId for these to use in transactions.

getTokensIssuedByAddress isn't finding any token based on CA. 

How do I get a token based on CA?
For example this token;
https://dexscreener.com/tron/txpp6hxd3cpcd5hsdmbc78iaicxrqijjm1

`https://tronweb.network/docu/docs/6.0.0-beta.3/API%20List/trx/getTokensIssuedByAddress`

**Comment by Satan-web3** [comment]
`getTokensIssuedByAddress` is used for token 10 but Bull Tron is token 20 type.

**Comment by catstersol** [comment]
@Satan-web3   what am I suppose to use then?   How do I get token Id for contract address?

**Comment by unicornonea** [comment]
TRC20 has no meaning of `token Id` , contract address is the only identification.
