### ISSUE TITLE
TronWeb does not have a method called getContract

### ISSUE THREAD

**Issue by topwood** [tronprotocol/tronweb#554]
![image](https://github.com/user-attachments/assets/f2a30ac6-17a1-4b23-8fc4-1c215c398248)

via: https://docs.sun.io/developers/swap/sunswap-overview

tronWeb does not have a method called getContract at all：
![image](https://github.com/user-attachments/assets/4601b14c-871d-459e-bd97-632175c9a737)

Original request: Use the tron web SDK to implement Sunswap trading.

**Comment by topwood** [comment]
"dependencies": {
    "@noble/secp256k1": "^1.7.1",
    "tronweb": "^5.3.2"
  }

**Comment by Satan-web3** [comment]
The documentation gives wrong api. Please use `let contract = await tronWeb.contract([], 'TXk8rQSAvPvBBNtqSoY6nCfsXWCSSpTVQF')`
