### ISSUE TITLE
Compilation error v5.3.2 MODULE_NOT_FOUND and ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by daochild** [tronprotocol/tronweb#556]
1) After install tronweb dependancy missing

Error: Cannot find module '@noble/secp256k1'
Require stack:  C:\Users\user\Desktop\check_typescript_export\node_modules\tronweb\dist\TronWeb.node.js
code: 'MODULE_NOT_FOUND'

2) If try to install missing package compilation ok, but execution of file is

C:\Users\user\Desktop\check_typescript_export\node_modules\tronweb\dist\TronWeb.node.js:315
undefined
 

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\user\Desktop\check_typescript_export\node_modules\@noble\secp256k1\index.js from C:\Users\user\Desktop\check_typescript_export\node_modules\tronweb\dist\TronWeb.node.js not supported.
Instead change the require of index.js in C:\Users\user\Desktop\check_typescript_export\node_modules\tronweb\dist\TronWeb.node.js to a dynamic import() which is available in all CommonJS modules.

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "NodeNext",     
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "types": ["node"],
    "lib": ["es2020", "dom"],
    "rootDirs": ["src"],
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "typeRoots": ["./node_modules/@types", "./src/**/*"],
    "noImplicitAny": false
  },
  "ts-node": {
    "esm": true
  }
}
```
package.json
```json
  "devDependencies": {
    "@daochild/tronweb-typescript": "^1.2.105",
    "@noble/secp256k1": "^2.1.0",
    "@types/node": "^22.5.4",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.4"
  },
  "dependencies": {
    "tronweb": "^5.3.2"
  },
```
```bash
$ node --version
v22.6.0
$ npm --version
10.8.3
OS: W10
```
P.S. if compile code with commonjs ERR_REQUIRE_ESM still presents, node v20 same errors

**Comment by Satan-web3** [comment]
See [here](https://github.com/tronprotocol/tronweb/issues/533#issuecomment-2216950995) for solution.
