### ISSUE TITLE
not able to instantiate tronWeb

### ISSUE THREAD

**Issue by kirat79** [tronprotocol/tronweb#562]
so i followed the docs

npm install tronweb

const TronWeb  = require('tronweb')

const tronWeb = new TronWeb({
  fullHost: 'https://api.shasta.rongrid.io'
});

when i run the backend , there shown is
const tronWeb = new TronWeb({
                ^

TypeError: TronWeb is not a constructor

please somebody help fast

**Comment by Satan-web3** [comment]
TronWeb has released v6.0.0 version which uses named import:
```js
const { TronWeb } = require('tronweb');
```
For more details, check out [here](https://tronweb.network/docu/docs/Migrating%20from%20v5)
