### ISSUE TITLE
Tronweb is not a constructor

### ISSUE THREAD

**Issue by Sam15766** [tronprotocol/tronweb#565]
Hi guys, I need some help. 

I am trying to make a script using tron network and when I am importing the network for utilization I keep getting the error tronweb is not a constructor. 

I am using 6.0.0 and this is what it looks like 

const tronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io',
    privateKey: '', // Replace with your actual private key

please help me, ive tried uninstalling and re installing tron and clearing caches and everuthing

**Comment by Satan-web3** [comment]
TronWeb has released v6.0.0 version which uses named import:
```js
const { TronWeb } = require('tronweb');
or
import { TronWeb } from 'tronweb';
```

For more details, check out [here](https://tronweb.network/docu/docs/Migrating%20from%20v5)
