### ISSUE TITLE
Invalid origin address provided

### ISSUE THREAD

**Issue by monkeychoi** [tronprotocol/tronweb#567]
const account = await tronWeb.createAccount(); 
I ran the code to create an address and ran the code below to activate the Account, but the following error appears and the Account is not activated. What's the problem?

error is 'Invalid origin address provided'

const transaction = await tronWeb.transactionBuilder.createAccount('TQFGXDePypFhvWPYF.................');    
const signedTransaction = await tronWeb.trx.sign(transaction);
const result = await tronWeb.trx.sendRawTransaction(signedTransaction);

**Comment by Satan-web3** [comment]
I guess you didn't provide privateKey when you init tronWeb instance, thus the transactionBuilder can't get the origin address. All you need to do is to provide an existing privateKey when you init tronWeb.

**Comment by rsuriano** [comment]
@Satan-web3 what happens if I don't have the private keys in the same project? I generate unsigned transactions for all transactions and the kms signs them, we can't do the same for the address activation transaction?
