### ISSUE TITLE
 ^  TypeError: TronWeb.createAccount is not a function

### ISSUE THREAD

**Issue by Osub** [tronprotocol/tronweb#569]
let wallet = await TronWeb.createAccount();
                                   ^

TypeError: TronWeb.createAccount is not a function

**Comment by Osub** [comment]
这库真难用

**Comment by Satan-web3** [comment]
How you import TronWeb? Since TronWeb has released v6.0.0 version, you need to use named import like this:
```js
import { TronWeb } from 'tronweb';
```
