### ISSUE TITLE
多签交易怎么签名别人签名过的交易

### ISSUE THREAD

**Issue by w33d2023** [tronprotocol/tronweb#578]
我的流程是这样的  我设置了多签账户, 需要两个人进行签名才能进行交易

我现在的思路是 使用Java 发起交易, 并且第一个人在Java里面进行签名, 签名之后 我把这笔签名了一个人的交易给到前端, 然后前端对这笔交易 进行唤醒tronLink, 第二个人使用tronLink签名后 将该笔交易广播到区块链

请问我应该如何将16进制的交易信息, 反序列化为交易对象, 并且唤醒tronLink后, 使用tronLink去签名后, 进行广播交易呢

**Comment by Satan-web3** [comment]
We'll support deserialize triggerSmartContract in v6.0.1, please wait for the new version.

**Comment by Class-Spotec** [comment]
现在版本支持吗？
