### ISSUE TITLE
How to invoke TronLink to sign a transaction that has already been signed by someone else and broadcast it to the blockchain?

### ISSUE THREAD

**Issue by w33d2023** [tronprotocol/tronweb#579]
How to invoke TronLink to sign a transaction that has already been signed by someone else and broadcast it to the blockchain?

**Comment by unicornonea** [comment]
You could use `tron.tronWeb.trx.multiSign()` function which is 
exposed by TronLink wallet to sign your transaction. Then use `tron.tronWeb.trx.sendRawTransaction(signedTranscation)` to broadcast it to the blockchain.
