### ISSUE TITLE
how to caculate the rate between BANDWIDTH Resource Amount and Staked Asset	Amount

### ISSUE THREAD

**Issue by godlovericea** [tronprotocol/tronweb#581]
I want 100 BANDWIDTH , how many Assets should be Staked ? How to query it ?
 
such as a pic below:
![image](https://github.com/user-attachments/assets/28ea906b-36ef-4aaa-bc25-0c61e318c784)

**Comment by Satan-web3** [comment]
You can get the rate by calling `tronWeb.trx.getAccountResources`. How many bandwidth you can get by staking 1 trx is the result of `TotalNetLimit/TotalNetWeight`.

**Comment by godlovericea** [comment]
Thanks. I get it
