### ISSUE TITLE
Is that possible to withdraw all TRX left in the wallet?

### ISSUE THREAD

**Issue by buigiaanfb1** [tronprotocol/tronweb#582]
Hi guys,
Is there any built-in function to do this? Because currently I'm doing that manually by calculate the fee.
It would be great if we have a function to do that

**Comment by laurenceja** [comment]
@buigiaanfb1 Transferring TRX transaction only consumes bandwidth, and each account have 600 free bandwidth a day, and it is enough for one TRX transferring transaction. So it is ok to withdraw all TRX left in your wallet. You can query the account's resource by [getaccountresource](https://developers.tron.network/reference/getaccountresource) API.

**Comment by buigiaanfb1** [comment]
ah I see now. Thanks @laurenceja
