### ISSUE TITLE
Which api can I get the delegated energy amount in a delegation transaction and obtained energy amount in a staking transaction?

### ISSUE THREAD

**Issue by morty6688** [tronprotocol/tronweb#586]
1. delegated energy like this, I can't find how to get the "2042.91 energy" when using GetTransactionById api. 
transaction url: https://nile.tronscan.org/#/transaction/d1aba9f094d9ae600421bead1e8720d917905eb7f02b85ea6e538285d0d47980
![image](https://github.com/user-attachments/assets/8893119f-718d-4890-83d7-75c886623919)
2. I can't even get obtained energy amount in tronscan page after staking, like this url: https://nile.tronscan.org/#/transaction/bb1213795594f0762b951a65f97e29c41ba217a103df45b7066ed20430a923b0

**Comment by morty6688** [comment]
Well, now I have known that this energy is calculated from a formula(`The amount of energy obtained = the amount of TRX staked for obtaining energy / the total amount of TRX staked for obtaining energy in the whole network * 180_000_000_000`), and it will change everyday. 
The next problem is, which api can I get `the total amount of TRX staked for obtaining energy in the whole network`?

**Comment by Stan202310** [comment]
You can use `tronWeb.trx.getAccountResources` api. The TotalEnergyWeight field is for the total amount of TRX staked for obtaining energy in the whole network.

**Comment by morty6688** [comment]
> You can use `tronWeb.trx.getAccountResources` api. The TotalEnergyWeight field is for the total amount of TRX staked for obtaining energy in the whole network.

Thx for ur reply! I still have a question, the response returned(2467172490) by this API seems to be not completely consistent with the [tronscan](https://nile.tronscan.org/#/data/charts/trx/staked) query result(2,467,089,118). What is the update frequency of this field(TotalEnergyWeight)?

**Comment by Stan202310** [comment]
The field is updated on every block time.
