### ISSUE TITLE
Tronlink android application uses tronweb?

### ISSUE THREAD

**Issue by SergeyAnkarenko** [tronprotocol/tronweb#74]
Hello, I have a question

I can't find sources of tronlink android application.
I am wondering if it uses tronweb library to sign messages, transactions

I realized that tronlink chrome extension signed message is different from one which is generated by tronlink android application. Furthermore, I noticed that `trx.verifyMessage(trx.signMessage)` returns true for tronlink chrome extension but, it's always false when using interface provided by android tronlink application, so it seems verify function doesn't much sign function

I will be very glad to get any help or hits related to this subject

**Comment by StarLXL** [comment]
It may be that tronlink android application uses an inconsistent version of tronweb.
