### ISSUE TITLE
error: 'CONTRACT_VALIDATE_ERROR', message: 'contract validate error : Owner no asset!'

### ISSUE THREAD

**Issue by malenchelon** [tronprotocol/tronweb#79]
![method send](https://user-images.githubusercontent.com/16664028/80807937-091a3580-8bdc-11ea-9c17-ea4f0aa02d53.png)

```
const TronWeb = require('tronweb');
const tronWeb = new TronWeb({
	fullHost: 'https://api.shasta.trongrid.io',
	privateKey: 'privatekey'
});

const userBalance = await tronWeb.contract().at('contractaddress');
	const sendf = await userBalance
		.registerStudent(param1, param2 .... paramn)
		.send({
			feeLimit: 100_000_000,
			callValue: 0,
			tokenId: 1000036,
			tokenValue: 100,
			shouldPollResponse: true
		})
		.then((res) => console.log(res))
		.catch((ex) => console.log(ex));
```

this is my code im getting the above error

i can able to use call() method and get the data in blockchain which is posted from tron ide

**Comment by StarLXL** [comment]
It's possible that you don't have enough 1000036 assets in your address.
Can you provide that address?

**Comment by malenchelon** [comment]
yes, the tokenid i have given is not there so i removed tokenid,tokenvalue,shouldpollresponse from this and worked like charm. Thanks
