### ISSUE TITLE
contract balanceOf call, response "owner_address isn't set."

### ISSUE THREAD

**Issue by XiChaoSir** [tronprotocol/tronweb#90]
```js
// init tronWeb
const TronWeb = require('tronweb')

const tronWeb = new TronWeb({
  fullNode: 'https://api.trongrid.io',
  solidityNode: 'https://api.trongrid.io',
})

// read trc20 account balance
let contract = await tronWeb.contract().at("TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"); 
let result = await contract.balanceOf('TZ13rQk53DDvK2pR4nfBLyuYTR4EGAFBwT').call();

// response error
//(node:49919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): class java.security.InvalidParameterException : owner_address isn't set
```

**Comment by CQBinh** [comment]
@XiChaoSir if you are developing at serverside, let pass the `privateKey` to `TronWeb`:
```
const tronWeb = new TronWeb({
  fullNode,
  solidityNode,
  eventServer,
  privateKey
})
```

**Comment by keesdewit82** [comment]
Setting the private key is not a great advise to be honest. You should try to avoid keeping your private key available as a string in your application. Keep it on a secure device for example. Not in the memory of your software. Anyway, this issue can also be fixed by applying the following code:

```tronWeb.setAddress('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t');```

So that would be:

```// init tronWeb
const TronWeb = require('tronweb')

const tronWeb = new TronWeb({
  fullNode: 'https://api.trongrid.io',
  solidityNode: 'https://api.trongrid.io',
})

// set the owner address
tronWeb.setAddress('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t');

// read trc20 account balance
let contract = await tronWeb.contract().at("TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"); 
let result = await contract.balanceOf('TZ13rQk53DDvK2pR4nfBLyuYTR4EGAFBwT').call();```

**Comment by joadr** [comment]
Why would you need to set an address for calling a balanceOf?

**Comment by kricha** [comment]
any news here?

**Comment by G33kNoob** [comment]
> tronWeb.setAddress('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t');

worked thanks

**Comment by MonchiLin** [comment]
In addition to the above methods, you can also use `transactionBuilder.triggerSmartContract`.

```
const balanceOfRes = await this.tronWeb.transactionBuilder
  .triggerSmartContract(
    "Contract Address",
    "balanceOf(address)",
    options,
    [
      {
        type: 'address',
        value: "Balance Of Wallet Address"
      }
    ],
    "Wallet Address"
);
```

For example:
```
// Get USDT balance of TSu8rSjd86uhtY7EVNazZsuEA7p1DdohZ8
const balanceOfRes = await this.tronWeb.transactionBuilder
  .triggerSmartContract(
    "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    "balanceOf(address)",
    options,
    [
      {
        type: "address",
        value: "TSu8rSjd86uhtY7EVNazZsuEA7p1DdohZ8"
      }
   ],
    "TSu8rSjd86uhtY7EVNazZsuEA7p1DdohZ8"
);

```
Docs: https://developers.tron.network/reference/tronweb-triggersmartcontract

**Comment by Jo-Chris** [comment]
Any explanation as to why we have to set an address here?

**Comment by itxtoledo** [comment]
tron is funny

**Comment by YaminZheng** [comment]
调用 .symbol 为什么需要 owner_address ??? 实在是难以理解

**Comment by zachariahevans174** [comment]
$$$

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zachariahevans174** [comment]
Ni hao 🫡 🤷🙏🙂‍↕️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zohouri** [comment]
>[If you only want to query information from the TRON Network blockchain without signing a transaction with instantiated tronweb, such as getTransactionInfo, triggerconstantcontract, you can pass a public private key such as 01 to instantiate TronWeb.](https://tronweb.network/docu/docs/quickstart/#instantiation)

**Comment by MerdyNumber1** [comment]
You can actually pass `from` param into `call`

```
const rawBalance = await contract
        .balanceOf(address)
        .call({ from: address })
```
