### ISSUE TITLE
tronweb types

### ISSUE THREAD

**Issue by sergeyd108** [tronprotocol/tronweb#92]
Where can I get TS type definitions for tronweb?

**Comment by summertanh** [comment]
@sergeyd108 Do you need to create a tronWeb instance by typeScript?

**Comment by junhoyeo** [comment]
> @sergeyd108 Do you need to create a tronWeb instance by typeScript?

We also need the typings for the instance in the global Window object, which get injected if you integrate with [TronLink](https://developers.tron.network/docs/tronlink-integration).

**Comment by summertanh** [comment]
@junhoyeo try any

**Comment by FrameMuse** [comment]
I found this library - https://www.npmjs.com/package/tronweb.types
