### ISSUE TITLE
High vulnerability issue found when installing tronweb

### ISSUE THREAD

**Issue by marlonbrgomes** [tronprotocol/tronweb#99]
The elliptic library used should be upgraded to 6.5.3 or later in order to get this issue solved. The version that is comming from tronweb's package.json is 6.4.1 (https://github.com/tronprotocol/tronweb/blob/master/package.json#L28).

Also, ethers library isnt using this elliptic anymore on latest version.

My recommendation:
elliptic to 6.5.3
ethers to 5.0.8

![image](https://user-images.githubusercontent.com/8737412/90416057-5a194100-e088-11ea-86bf-4de22a319be3.png)

Elliptic issue: https://github.com/indutny/elliptic/issues/226
https://vigilance.fr/vulnerability/Node-js-elliptic-information-disclosure-via-ECDSA-Signature-Malleability-32975

Thanks in advance.

**Comment by summertanh** [comment]
Thank you for your advice. It will update in next version soon.
